### ISSUE TITLE
Gitlab registry - error parsing HTTP 404 response body: invalid character

### ISSUE THREAD

**Issue by weaktyper** [sameersbn/docker-gitlab#1025]
I'm using letsencrypt, nginx-proxy and gitlab with gitlab-registry.
I can't open the gitlab-registry page of a project without getting a 500 error. Gitlab is
working fine and the url https://$REGISTR_DOMAIN/v2/ seems to work when sent a curl request except that it is not authorised. ie ` https://$REGISTR_DOMAIN/v2/` doesn't have a tcp connection refused which is why I can't understand why gitlab is having that problem.

This is the error in ` /home/git/gitlab/log/production.log` of the gitlab container.
```
Faraday::ConnectionFailed (Failed to open TCP connection to $REGISTR_DOMAIN:443 (Connection refused - connect(2) for "$REGISTR_DOMAIN" port 443)):
  lib/container_registry/client.rb:19:in `repository_tags'
  lib/container_registry/repository.rb:22:in `manifest'
  lib/container_registry/repository.rb:31:in `tags'
  app/controllers/projects/container_registry_controller.rb:8:in `index'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
```

This is the relevant parts of the docker-compose.yml
```
version: '2'
services:
  redis:
    ...

  postgresql:
    ...

  gitlab:
    image: sameersbn/gitlab:$GITLAB_VERSION
    container_name: gitlab
    network_mode: "bridge"
    links:
      - redis
      - postgresql
    depends_on:
      - redis
      - postgresql
    expose:
      - 80
    volumes:
      - ~/data/gitlab:/home/git/data
      - ~/data/gitlab/logs:/var/log/gitlab
      - ~/certificates:/certs/
    environment:
      - VIRTUAL_HOST=$GIT_DOMAIN
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=nohttp
      - LETSENCRYPT_HOST=$GIT_DOMAIN
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - SSL_SELF_SIGNED=false

      - GITLAB_REGISTRY_ENABLED=true
      - GITLAB_PROJECTS_CONTAINER_REGISTRY=true
      - GITLAB_REGISTRY_ISSUER=gitlab-issuer
      - GITLAB_REGISTRY_HOST=$REGISTRY_DOMAIN
      - GITLAB_REGISTRY_API_URL=https://$REGISTRY_DOMAIN
      - GITLAB_REGISTRY_KEY_PATH=/certs/$REGISTRY_DOMAIN.key
      - GITLAB_REGISTRY_PORT=443
      - SSL_REGISTRY_KEY_PATH=/certs/$REGISTRY_DOMAIN.key
      - SSL_REGISTRY_CERT_PATH=/certs/$REGISTRY_DOMAIN.crt

  registry:
    restart: always
    image: registry:$REGISTRY_VERSION
    container_name: gitlab-registry
    network_mode: "bridge"
    volumes:
      - ~/data/gitlab/shared/registry:/registry
      - ~/certificates:/certs
    environment:
      - VIRTUAL_HOST=$REGISTRY_DOMAIN
      - LETSENCRYPT_HOST=$REGISTRY_DOMAIN
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL

      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
      - REGISTRY_AUTH_TOKEN_REALM=https://$REGISTRY_DOMAIN/jwt/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
      - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/$REGISTRY_DOMAIN.crt
      - REGISTRY_STORAGE_DELETE_ENABLED=true

networks:
  default:
    external:
      name: bridge
```

Anyone have any idea or have a working configuration? 

Perhaps it's some problem with the certificates but they do exist.
