### ISSUE TITLE
Registry - dial tcp: too many colons

### ISSUE THREAD

**Issue by vitosans** [sameersbn/docker-gitlab#1085]
Finally got around to enabling Registry support in gitlabs this morning and I am running in to a very interesting error when trying to login to the registry for the first time.

```sh
docker login gitlab.example.com:5500
Username: joe
Password: ***********

Error response from daemon: Get https://gitlab.example.com:5500/v2/: Get https://gitlab.example.com:10080:/jwt/auth?account=joe&client_id=docker&offline_token=true&service=container_registry: dial tcp: too many colons in address gitlab.example.com:10080:
```

I think this is a golang error. I have double checked all my configs and I don't have a trailing ":" in any of my definitions. Has anyone else seen this?

**Comment by vitosans** [comment]
Here are the parts of my compose that that are relevant:

Gitlab:
```yaml
ports:
     - "80:80"
     - "10080:80"
     - "5500:5500"
      - "10022:22"
      - "443:443"
- GITLAB_REGISTRY_ENABLED=true
- GITLAB_REGISTRY_HOST=gitlab.example.com
- GITLAB_REGISTRY_PORT=5500
- GITLAB_REGISTRY_API_URL=http://registry:5000
- GITLAB_REGISTRY_KEY_PATH=/home/git/data/certs/gitlab.key
- SSL_REGISTRY_KEY_PATH=/home/git/data/certs/gitlab.key
- SSL_REGISTRY_CERT_PATH=/home/git/data/certs/gitlab.crt
```

Registry:
```yaml
registry:
  restart: always
  image: registry:2.4.1
  volumes:
    - /mnt/docker-volume/gitlab/shared/registry:/registry
    - /mnt/docker-volume/gitlab/gitlab/certs:/certs
  environment:
    - REGISTRY_LOG_LEVEL=info
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
    - REGISTRY_AUTH_TOKEN_REALM=http://gitlab.example.com:10080/jwt/auth
    - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
    - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/ca.crt
    - REGISTRY_STORAGE_DELETE_ENABLED=true
```
