### ISSUE TITLE
ERROR: Service 'gitlab' has a link to service 'gitlab-redis:redisio' which is undefined.

### ISSUE THREAD

**Issue by worldask** [sameersbn/docker-gitlab#1106]
I tried to run docker-gitlab using docker-compose, following is my docker-compose.yml

 ```
 redis:
    image: sameersbn/redis:latest
    container_name: gitlab-redis
    restart: always
    volumes:
      - /data/gitlab/redis:/var/lib/redis

  gitlab:
    image: sameersbn/gitlab:latest
    container_name: gitlab
    restart: always
    links:
      - gitlab-redis:redisio
    ports:
      - "80:80"
      - "10022:22"
    hostname: gitlab.example.com
    environment:
      - GITLAB_HOST=gitlab.example.com
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=xxx
      - GITLAB_SECRETS_SECRET_KEY_BASE=xxx
      - GITLAB_SECRETS_OTP_KEY_BASE=xxx
      - DB_ADAPTER=mysql2
      - DB_HOST=172.18.0.1
      - DB_NAME=gitlabhq_production
      - DB_USER=gitlab
      - DB_PASS=xxx
    volumes:
      - /data/gitlab:/home/git/data
```

When I ran `docker-compose up -d`, it gave this error message
`ERROR: Service 'gitlab' has a link to service 'gitlab-redis:redisio' which is undefined.`

What's wrong?
