### ISSUE TITLE
GitLab unable to connect with database in Kubernetes

### ISSUE THREAD

**Issue by GarbageYard** [sameersbn/docker-gitlab#1342]
I am trying to use separate containers for GitLab, Redis and PostgreSQL in Kubernetes with Gluster. I am launching the three containers in the order PostgreSQL, Redis and then GitLab. First two work fine but when i try launching GitLab, it's somehow not finding the database configuration.

```
[root@cent-gluster-workstation ~]# kubectl logs gitlab-3743104516-plk3x -p
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
ERROR:
  Please configure the database connection.
  Refer http://git.io/wkYhyA for more information.
  Cannot continue without a database. Aborting...
```

I confirmed that i was able to telnet from within the GitLab pod to PostgreSQL pod on port 5432.

```
root@gitlab-1182173148-t47fj:/home/git/gitlab# telnet postgresql 5432
Trying 10.42.154.36...
Connected to postgresql.default.svc.cluster.local.
Escape character is '^]'.
```

Deployment and service configuration for GitLab and PostgreSQL:

```
[root@cent-gluster-workstation ~]# cat postgresql-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: gitlabhq_production
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: gitlab
        image: postgres:9.6.3
        name: postgresql
        volumeMounts:
        - name: gluster-vol1
          mountPath: /var/lib/postgresql
        resources: {}
      volumes:
      - name: gluster-vol1
        persistentVolumeClaim:
          claimName: gluster-dyn-pvc
status: {}


[root@cent-gluster-workstation ~]# cat postgresql-service.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgresql
status:
  loadBalancer: {}


[root@cent-gluster-workstation ~]# cat gitlab-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gitlab
    spec:
      containers:
      - env:
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: 110Ect4ClClGBH06RSEQm4uKCxbpCyPzxfdLORkkssrStDnrQgpSSV
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: MWxqmqqQkG1EXz9iz7Up4tEGBIEtFjxr1rL1Ry1rWCTWBjw3qxtvOM
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: 2KOeHYHNXB4r2XDZzy3XVrH2r0t6j71MBDUmfx4FxRPqjI5KZ9j4Md
        - name: GITLAB_SSH_PORT
          value: "10022"
        image: sameersbn/gitlab:9.3.9
        name: gitlab
        volumeMounts:
        - name: gluster-vol1
          mountPath: /home/git/data
        ports:
        - containerPort: 443
        - containerPort: 80
        - containerPort: 22
        resources: {}
      volumes:
      - name: gluster-vol1
        persistentVolumeClaim:
          claimName: gluster-dyn-pvc
status: {}
```

When i was using these three containers without Kubernetes and Gluster, i was able to get GitLab up and running by following the steps in the [Quick Start](https://github.com/sameersbn/docker-gitlab#quick-start) section of your GitLab setup. In this case, i was using volume mount path as `/srv/docker/gitlab/` for all three containers (GitLab, Redis and PostgreSQL).

In the current case, as you can see in the deployment and service YAMLs above, i am using Gluster volume to map the container paths. Does this has anything to do with the issue or something else is wrong somewhere?

PS: I have to stick to the above GitLab and PostgreSQL version because i need to export data from an existing GitLab omnibus setup which is running the above versions for GitLab and PostgreSQL.
