### ISSUE TITLE
GITLAB_MONITORING_SIDEKIQ_EXPORTER does not work

### ISSUE THREAD

**Issue by krlng** [sameersbn/docker-gitlab#1350]
I activated the sidekiq exporter settings using: GITLAB_MONITORING_SIDEKIQ_EXPORTER_ENABLED = true and leaving the other GITLAB_MONITORING_SIDEKIQ_EXPORTER_* settings untouched. This seems to correctly set the config/gitlab.yml: 
```
sidekiq_exporter:
  monitoring:
    # Time between sampling of unicorn socket metrics, in seconds
    unicorn_sampler_interval: 10
    # IP whitelist to access monitoring endpoints
    ip_whitelist:
      - 0.0.0.0/8
    # Sidekiq exporter is webserver built in to Sidekiq to expose Prometheus metrics
    sidekiq_exporter:
      enabled: true
      address: 0.0.0.0
      port: 3807
```

However this takes no effect. I don't see any related processes and port 3807 is not allocated: 
```
sudo lsof -i -P -n
COMMAND PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
nginx   600 root    9u  IPv4 9601834      0t0  TCP *:80 (LISTEN)
nginx   600 root   10u  IPv6 9601835      0t0  TCP *:80 (LISTEN)
sshd    601 root    4u  IPv4 9601848      0t0  TCP *:22 (LISTEN)
sshd    601 root    5u  IPv6 9601849      0t0  TCP *:22 (LISTEN)
```

I tried to dig deeper, but since I don't know much about ruby I did not get to far.
