### ISSUE TITLE
gitlab-runner artifacts no such host

### ISSUE THREAD

**Issue by gimler** [sameersbn/docker-gitlab#1391]
i try to use artifacts for my job but it fails with
```
ERROR: Uploading artifacts to coordinator... error  error=couldn't execute POST against http://gitlab/api/v4/jobs/1134/artifacts?: Post http://gitlab/api/v4/jobs/1134/artifacts?: dial tcp: lookup gitlab on x.x.x.x:53: no such host id=1134 token=4qosTVn7
```

i think the gitlab-runner can't resolve correctly gitlab. he use the container name and not the `GITLAB_HOST` `GITLAB_PORT` `GITLAB_HTTPS` envs.

docker-compose.yml
```
 gitlab:
    restart: unless-stopped
    image: sameersbn/gitlab:10.1.0
    depends_on:
      - redis
      - postgresql
    expose:
      - "80"
    ports:
      - "10022:22"
    environment:
      - GITLAB_HOST=gitlab.mydomain.com
      - GITLAB_PORT=443
      - GITLAB_HTTPS=true
...
  gitlab-runner:
    restart: unless-stopped
    image: gitlab/gitlab-runner:alpine-v10.1.0
    volumes:
      - "$PWD/config/gitlab-runner/config.toml:/etc/gitlab-runner/config.toml"
      - "$PWD/config/gitlab-runner/config.json:/root/.docker/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

.gitlab-ci.yml
```
image: docker:17.05.0-git

variables:
  DOCKER_DRIVER: overlay
  COMPOSE_HTTP_TIMEOUT: '120'
  GIT_STRATEGY: clone

cache:
  paths:
  - vendor/

services:
  - docker:17.05.0-dind

build_image:
  stage: build
  script:
...
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - tests/_output
    untracked: true
    when: always
```
