### ISSUE TITLE
Testing ssh with local network work but externally will ask for password.

### ISSUE THREAD

**Issue by hotrice** [sameersbn/docker-gitlab#1469]
I have tested Gitlab internally and everything is working. Ldap, push and pull, etc. I have set up a domain and connect to Gitlab just fine and working using https://gitlab.mydomain.com. The problem I am running into is cloning, pushing, and pulling using the domain name. example:  Existing Git repository
cd existing_repo
git remote add origin git@gitlab.mydomain.com:username/my-project.git
git push -u origin --all
Once it does the push, it requested me to enter the password, but if I do git remote add origin git@local IP of Gitlab it doesn't require me to enter the password because the ssh key authentication is working. I have tested with the command ssh -T git@mylocalIp and it welcome me but if I do ssh -T git@gitlab.mydomain.com it would prompt me for the password.

**Comment by jrief** [comment]
having the same problem using the current version.

**Comment by balajidl** [comment]
May be it got to do with ports mapped. This is how part of my docker-compose looks like.
I mapped port 22 from docker to parent server (Server running docker).
For ssh to the parent server, I changed it to [other port](https://in.godaddy.com/help/changing-the-ssh-port-for-your-linux-server-7306)

```
  gitlab:
    restart: always
    image: sameersbn/gitlab:latest
    depends_on:
    - redis
    - mysql
    ports:
    - "80:80"
    - "22:22"
   ....
   ....
```

Can this be of some help?
