### ISSUE TITLE
Urgent help please: Not able to run gitlab 10.3.6 due Mysql error "count of mysql.user is wrong"

### ISSUE THREAD

**Issue by balajidl** [sameersbn/docker-gitlab#1486]
I am using gitlab with mysql and my docker-compose will look like:
```
  mysql:
    restart: always
    image: sameersbn/mysql:latest
    volumes:
    - /mnt/data/docker/gitlab/mysql:/var/lib/mysql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=********
    - DB_NAME=gitlabhq_production
```
After docker-compose pull, and when i run docker-compose up, we get the following error:

```
mysql_1   | Creating database "gitlabhq_production"...
mysql_1   | Granting access to database "gitlabhq_production" for user "gitlab"...
mysql_1   | ERROR 3009 (HY000) at line 1: Column count of mysql.user is wrong. Expected 45, found 42. Created with MySQL 50554, now running 50721. Please use mysql_upgrade to fix this error.
```
Kindly help us as we are using your docker images for our production server.
CC: @sameersbn @solidnerd

**Comment by balajidl** [comment]
I also tried adding the command 'mysql_upgrade'
```
    image: sameersbn/mysql:latest
    command: mysql_upgrade
```
but getting the error "`mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111) while connecting to the MySQL server`"

**Comment by balajidl** [comment]
Resolved it by using mysql image and then connecting to mysql shell to run the mysql_upgrade

1. Created one docker-compose for mysql alone.
```
version: '2'

services:

  mysql:
    restart: always
    image: mysql
    volumes:
    - /mnt/data/docker/gitlab/mysql:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: "gitlabhq_production"
      MYSQL_USER: "gitlab"
      MYSQL_PASSWORD: "*******"
```

2. started it by running docker-compose up
3. connected to the running instance by using the command `docker exex -it <doc ps id for mysql> bash` to get shell access
4. Inside the shell ran `mysql_upgrade`. It upgraded all tables in mysql
5. Now copied the same docker-compose to my gitlab docker-compose. (this means, I used mysql image and not sameersbn image)
6. started docker and gitlab is working fine again
