### ISSUE TITLE
default GITLAB_SSH_PORT leads to wrong SSH repository URLs

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [sameersbn/docker-gitlab#1596]
Starting the container with no `GITLAB_SSH_PORT` configured (using the default 22) leads to wrong ssh URLs for projects.

Example:
`git@example.com:path/to/my/project.git` --> `:` whitout port

Expected paths:
* either: `ssh://git@example.com/path/to/my/project.git`
* or: `ssh://git@example.com:22/path/to/my/project.git`

The `ssh://` prefix is also missing. Is this the expected behavior?

Using a different port generates correct URLs (`:<PORT>/`).

The `GITLAB_PORT` environment variable is also not provided, but here the HTTP URLs are correct.

**Comment by spritle** [comment]
In docker-compse we have the ports like
```
  gitlab:
    restart: always
    image: sameersbn/gitlab:latest
    depends_on:
    - redis
    - mysql
    ports:
    - "80:80"
    - "2525:2525"
    - "22:22"
```

This means, we gave port 22 for gitlab and we used some other port for ssh login.

Can this help your case?
