### ISSUE TITLE
The specified backup does not exist

### ISSUE THREAD

**Issue by ChunAllen** [sameersbn/docker-gitlab#1597]
I created a backup using `docker-compose run --rm gitlab app:rake gitlab:backup:create`
and it generated a a tar file `1526281372_gitlab_backup.tar`

but when I try to restore the file 
`docker-compose run --rm gitlab app:rake gitlab:backup:restore BACKUP=1526281372`

it returns this 
```
Starting gitlabdocker_redis_1 ... done
Initializing logdir...postgresql_1 ... done
Initializing datadir...
Generating OpenSSH host keys... RSA1 RSA DSA ECDSA ED25519
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Running raketask gitlab:backup:restore...
no backups found
The specified backup doesn't exist!
```

**Comment by spritle** [comment]
Check the file really exist inside your docker folder for gitlab.
It will be generally at <docker volume>/gitlab/backups

**Comment by ChunAllen** [comment]
@spritle I saw there's a backup tar file in `/gitlab/backups` I tried again to restore but still the return is 
`the specified backup doesn't exist` I run the command `docker-compose run --rm gitlab app:rake gitlab:backup:restore BACKUP=1526281372` in `/gitlab/backups` Do I miss something here?

**Comment by ChunAllen** [comment]
My `docker-compose.yml` is this 
```
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=
    - DB_NAME=
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.12.4
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
```
