### ISSUE TITLE
sameersbn/redis loop restarting

### ISSUE THREAD

**Issue by justinushermawan** [sameersbn/docker-gitlab#1657]
I got a problem with `sameersbn/redis` container, it keeps restarting whenever I restart the container, can't start normally. I've already removed all containers, including gitlab, postgresql, and redis but the problem still appears. Gitlab itself and postgres have no problem, only redis.

Anyone has an idea how does this problem come?

**Comment by thomaskr** [comment]
The problem seems to be caused by a new version of redis that runs in protected mode.
Try to add `--protected-mode no` to the command line. For example:
```
services:
  redis:
    image: sameersbn/redis:latest
    command:
    - --loglevel warning --protected-mode no
```
