### ISSUE TITLE
Multiple address or ip in GITLAB_TRUSTED_PROXIES variable

### ISSUE THREAD

**Issue by s4l3h1** [sameersbn/docker-gitlab#1689]
What is the correct syntax to add multiple trusted_proxies in the GITLAB_TRUSTED_PROXIES variable?
I want to use sth like this:
```
version: '3.5'
services:
  gitlab:
    restart: always
    image: sameersbn/gitlab
    environment:
*** a lot of conf ***
    - GITLAB_TRUSTED_PROXIES='192.168.100.0/24','x.x.x.x'
```
but I got this in config/gitlab.yml:
```
    trusted_proxies:
      - '192.168.100.0/24','x.x.x.x'

```

I want to use two or more trusted_proxies, But I can't, What is the solution?
