### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by smoebody** [sameersbn/docker-gitlab#1726]
When the Gitlab-Runner tries to upload large artifacts (>100MB) it gets 
```
ERROR: Uploading artifacts to coordinator... too large archive  id=996 responseStatus=413 Request Entity Too Large status=413 Request Entity Too Large token=WEzVpnfj
FATAL: Too large                                   
ERROR: Job failed: exit code 1
```
This is appearently due to nginx-configuration. I do not know, where this could be set wrong but i know definetely that it must be the nginx from the gitlab-container.

**Comment by smoebody** [comment]
The gitlab-runner is a docker-container in the same network as gitlab. So the upload is done via http-post by the *gitlab-runner-helper*. If you want to test, i suggest the following.

1. create a new branch of an existing project which already has a ci-runner configured.
2. put the following job in the `.gitlab-ci.yml`:
```yaml
stages:
- build

build_artifact:
  stage: build
  image: alpine:3.8
  script: |
    dd if=/dev/urandom of=artifact.bin bs=1M count=256
  artifacts:
    paths:
    - "artifact.bin"
    expire_in: "1min"
  tags:
  - docker
```
*Assuming you have a ci-runner as docker-executor taking jobs tagged with* docker *this job creates a random file of 256MB size and uploads it as job-artifact.*

This fails in my gitlab-setup.
