### ISSUE TITLE
Can't get working the docker registry

### ISSUE THREAD

**Issue by zerr0s** [sameersbn/docker-gitlab#1737]
Hi, forgive me for my bad english.

I can't get working the inbuilt docker registry. I don't know why. I have real certificates (wildcard) for gitlab and registry. The small difference compared to the [doc](https://github.com/sameersbn/docker-gitlab/blob/master/docs/container_registry.md) is that I have an haproxy in front of gitlab and registry.

There are my conf:
```
registry:
    image: registry:2
    hostname: registry
    networks:
      - gitlab
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./data/gitlab/gitlab/certs/:/certs
      - ./data/gitlab/gitlab/shared/registry:/registry
    environment:
      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_AUTH_TOKEN_REALM=https://gitlab.mydomain.com/jwt/auth
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/gitlab.crt
      - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
```
and for gitlab:
```
gitlab:
    image: sameersbn/gitlab:11.3.4
    hostname: gitlab
    networks:
      - gitlab
    depends_on:
      - redis
      - db
      - registry
    links:
      - redis:redis
      - db:postgresql
      - registry:registry
    ports:
      - "8004:443"
      - "2222:22"
    volumes:
      - ./data/gitlab/gitlab:/home/git/data
    environment:
      - DEBUG=true
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_NAME=xxx
      - DB_USER=xxx
      - DB_PASS=xxxx
      - REDIS_HOST=redis
      - GITLAB_HOST=gitlab.mydomain.com
      - GITLAB_SECRETS_DB_KEY_BASE=xxxxx
      - GITLAB_SECRETS_SECRET_KEY_BASE=xxxx
      - GITLAB_SECRETS_OTP_KEY_BASE=xxxx
      - GITLAB_TIMEZONE=Paris
      - GITLAB_ROOT_PASSWORD=xxxxx
      - GITLAB_ROOT_EMAIL=xxxxx
      - GITLAB_EMAIL_DISPLAY_NAME="GitLab"
      - GITLAB_EMAIL=xxxxx
      - GITLAB_EMAIL_ENABLED=true
      - GITLAB_SIGNUP_ENABLED=false
      - GITLAB_BACKUP_DIR=/home/git/data/backups
      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00
      - GITLAB_SSH_HOST=gitlab.mydomain.com
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=2222
      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=false
      - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab.crt
      - SSL_KEY_PATH=/home/git/data/certs/gitlab.key
      - SSL_DHPARAM_PATH=/home/git/data/certs/dhparam.pem
      - SMTP_ENABLED=true
      - SMTP_HOST=xxxxx
      - SMTP_PORT=25
      - GITLAB_SHARED_DIR=/home/git/data/shared
      - GITLAB_ARTIFACTS_ENABLED=true
      - GITLAB_ARTIFACTS_DIR=/home/git/data/shared/artifacts
      - GITLAB_PROJECTS_CONTAINER_REGISTRY=true
      - GITLAB_REGISTRY_ENABLED=true
      - GITLAB_REGISTRY_HOST=registry.mydomain.com
      - GITLAB_REGISTRY_PORT=443
      - GITLAB_REGISTRY_API_URL=http://registry:5000
      - GITLAB_REGISTRY_KEY_PATH=/home/git/data/certs/gitlab.key
      - SSL_REGISTRY_KEY_PATH=/home/git/data/certs/gitlab.key
      - SSL_REGISTRY_CERT_PATH=/home/git/data/certs/gitlab.crt
```

When I try to use docker login:
`Error response from daemon: Get https://registry.domain.com/v2/: Get https://gitlab.mydomain.com/jwt/auth?account=xxxx&client_id=docker&offline_token=true&service=container_registry: Not Found`

And I have a 500 error on gitlab if I click on the registry button in left menu:
`Whoops, something went wrong on our end.`

Any idea ??
