### ISSUE TITLE
Gitlab 11.5+ Missing Pages Access Control

### ISSUE THREAD

**Issue by GJRTimmer** [sameersbn/docker-gitlab#1769]
In Gitlab 11.5 `Access Control` was introduced for gitlab pages.

[Official Documentation](https://docs.gitlab.com/ce/administration/pages/#access-control)

```ruby
 gitlab_pages['access_control'] = true
```

```yaml
 gitlab:
  pages:
    access_control = true
```

Request this to be controlled from an environment variable.
