### ISSUE TITLE
postgresql can't start:  Setting resolv.conf ACLs... pg_ctl: server did not start in time 

### ISSUE THREAD

**Issue by dotbalo** [sameersbn/docker-gitlab#1804]
I deployed gitlab to k8s and then used glusterfs for persistent storage, but postgresql could not be started after I restarted the cluster. The error is as follows:
````
 Initializing datadir...
Initializing certdir...
Initializing logdir...
Initializing rundir...
Setting resolv.conf ACLs...
pg_ctl: server did not start in time 
````
Other information:
![image](https://user-images.githubusercontent.com/25141522/49433811-c76e3b00-f7ed-11e8-97a5-dde02f44c97a.png)

````
[root@k8s-master01 ~]# docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@k8s-master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
[root@k8s-master01 ~]# uname -r
3.10.0-862.14.4.el7.x86_64
[root@k8s-master01 ~]# uname -a
Linux k8s-master01 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
````
postgresql-rc yaml
````
[root@k8s-master01 gitlab]# cat postgresql-rc.yml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
  namespace: public-service
spec:
  replicas: 1
  selector:
    name: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        name: postgresql
    spec:
      containers:
      - name: postgresql
        image: sameersbn/postgresql:10
        env:
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: passw0rd
        - name: DB_NAME
          value: gitlab_production
        - name: DB_EXTENSION
          value: pg_trgm
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-pg
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-pg
  namespace: public-service
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "gluster-heketi"
  resources:
    requests:
      storage: 5Gi
````

![image](https://user-images.githubusercontent.com/25141522/49434007-39468480-f7ee-11e8-96cf-4004c0140845.png)

I don't know what happened for postgresql. It used to be normal. I can't start it after I restarted the cluster.
