### ISSUE TITLE
Default username/password not working.

### ISSUE THREAD

**Issue by quasarj** [sameersbn/docker-gitlab#181]
I just pulled the sameersbn/gitlab:7.3.2-1 container and launched it with an external myself and red is server. It took a few minutes but it started correctly and I can reach the web interface. However the default login (as given in readme.md here) is not working. I tried a few other combinations I've seen around too (root, admin, admin@local.host, etc) and all fail.

Is anyone else experiencing this? Is something else possibly misconfigured on my system? I'm running on an Arch Linux host (no vms).

Thanks!

**Comment by jeffcichonski** [comment]
I had a similar issue. I could not log in with root/password. I did a bit of googling and found 5iveL!fe is used as the default password for gitlab in other implementations. root/5iveL!fe worked. 

Did gitlab make a change to default password?

**Comment by MatrixManAtYrService** [comment]
I ran across this issue because gitlab asked me to set a password on first startup, so I did.  Then, later, I tried to use 5iveLi!fe and it didn't work.  As it turns out, the password that I set during startup was the root password.

**Comment by INF800** [comment]
Hi! @quasarj @sameersbn @jeffcichonski @MatrixManAtYrService 

I used this `docker-compose up -d` to start the gitlab service in http://localhost:8929/

None of these combinations are working. Can anyone help me out ?

- root/5iveL!fe
- root/password
- root/root
- admin/5iveL!fe
- admin/password
- admin/admin
- admin@example.com/5iveL!fe
- admin@example.com/password
- admin@example.com/admin@example.com

### Additional information

**docker-compose.yml:**

```yml
web:
  image: 'gitlab/gitlab-ce:latest' 
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '8929:8929'
    - '2224:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
```
