### ISSUE TITLE
LFS fails to download after a restart of Gitlab

### ISSUE THREAD

**Issue by Nepoxx** [sameersbn/docker-gitlab#1871]
Whenever I restart our gitlab instance (upgrade, power failure, etc.), the LFS objects fail for all our repositories, one example:
```
Error downloading object: .readme/advanced.png (c0ef435): Smudge error: Error downloading .readme/advanced.png (c0ef435bda8d14f1e3a2575bc197f504dd8db378c909d37ff78ffb5446284009): [c0ef435bda8d14f1e3a2575bc197f504dd8db378c909d37ff78ffb5446284009] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
```

Our LFS assets are hosted on S3 (minio), they still exist and are accessible.

This problem resolves itself after quite a while, but I'm unsure what fixes it. `gitlab:lfs:check` finds no error.

Any idea on how to debug this would be highly appreciated!

Here's my docker-compose file:

```yaml
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:4.0.9-1
    command:
    - --loglevel warning
    volumes:
    - /raid2/docker/gitlabprod/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:10
    volumes:
    - /raid2/docker/gitlabprod/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS={omitted}
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:11.8.0
    depends_on:
    - redis
    - postgresql
    ports:
    - "10081:80"
    - "10444:443"
    - "10023:22"
    dns:
    - 192.168.5.48
    - 1.1.1.1
    volumes:
    - /raid2/docker/gitlabprod/gitlab:/home/git/data:Z
    environment:
    - DEBUG=false
    - prometheus_multiproc_dir=/dev/shm

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS={omitted}
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=america/new_york
    - GITLAB_TIMEZONE=UTC

    - UNICORN_WORKERS=13
    - GITLAB_UNICORN_MEMORY_MAX=1048576000
    - SIDEKIQ_MEMORY_KILLER_MAX_RSS=5000000
    - NGINX_WORKERS=4
    - NGINX_REAL_IP_RECURSIVE=on
    - NGINX_REAL_IP_TRUSTED_ADDRESSES=172.19.0.1

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=false

    - GITLAB_LFS_ENABLED=true
    - GITLAB_LFS_OBJECT_STORE_ENABLED=true
    - GITLAB_LFS_OBJECT_STORE_BACKGROUND_UPLOAD=true
    - GITLAB_LFS_OBJECT_STORE_DIRECT_UPLOAD=false
    - GITLAB_LFS_OBJECT_STORE_REMOTE_DIRECTORY={omitted}
    - GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_ACCESS_KEY_ID={omitted}
    - GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_SECRET_ACCESS_KEY={omitted}
    - GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_HOST={omitted}
    - GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_ENDPOINT={omitted}

   # Rest of file omitted
```
