### ISSUE TITLE
container keeps restarting with static IP in docker-compose.yml

### ISSUE THREAD

**Issue by saleemepoch** [sameersbn/docker-gitlab#1875]
I managed to get docker gitlab working with the docker-compose.yml file linked in read me.

But when I add static IP to it, gitlab container goes up to: Configuring gitlab...  and after a while it restarts and gets stuck in a loop.

All I added in docker-compose.yaml were the following lines:

  gitlab:
    restart: always
    networks:
      qnet-static-eth0-bf6875:
        ipv4_address: 192.168.95.7

and at the end:

networks:
  qnet-static-eth0-bf6875:
    external: true

The above lines work well for any other container. Only gitlab container seems to be stuck in a loop.

Any help will be greatly appreciated.

**Comment by saleemepoch** [comment]
If someone can tell me where Gitlab generates the log when it is `Configuring gitlab....` I may be able to find out what's causing this.

**Comment by saleemepoch** [comment]
Right, so I cannot seem to ping postgresql or redis from gitlab container, which makes me think that postgresql and redis are probably running on a different network.

So somehow I need to attach two network interfaces to gitlab, one that will connect to postgresql and redis and the other that will expose it to the outside world on a static IP.

**Comment by saleemepoch** [comment]
Ok, so the fix is as follows:

To run Gitlab on its own external static IP address, gitlab container needs to have two network interfaces:
1. default network that links gitlab, postgresql and redis together, and;
2. external network that sets a static IP address to gitlab

To achieve this in docker-composer we add something like the following to gitlab service:

```
  gitlab:
    restart: always
    image: sameersbn/gitlab:11.8.1
    networks:
      default: {}
      qnet-static-eth0-bf6875:
        ipv4_address: 192.168.95.7
```
We then define the aforementioned networks right at the end of our docker-compose.yml like so:

```
networks:
  default:
    driver: bridge
  qnet-static-eth0-bf6875:
    external: true
```

Obviously, remember to remove qnet-static-eth0-bf6875 with your own network.
