### ISSUE TITLE
create docker fail:(1e56cd69bb3f887600eee816cf2b9f992a2039e57e4b564c440e975d9ef26714): Error iptables FORWARD: Another app is currently holding the xtables lock;

### ISSUE THREAD

**Issue by zhangjingwen198817** [sameersbn/docker-gitlab#1921]
I start docker with xx.yml ,but it’s intermittent fail. how can i avoid?

`Error info:`
Creating udp-4  ... done
Creating udp-3  ... done
Creating udp-17 ... done
Creating udp-5  ... done
Creating udp-18 ... done
Creating udp-11 ... done
Creating udp-7  ... done
Creating udp-2  ... done
Creating udp-10 ... done
Creating udp-12 ... done
Creating udp-6  ... done
Creating udp-16 ... done
Creating udp-14 ... done
Creating udp-9  ... done
Creating udp-19 ... done
Creating udp-15 ... done
Creating udp-8  ... done
Creating udp-1  ... error
ERROR: for udp-1  Cannot start service udp-1: b'driver failed programming external connectivity on endpoint udp-1 (1e56cd69bb3f887600eee816cf2b9f992a2039e57e4b564c440e975d9ef26714): Error iptables FORWARD: Another app is currently holding the xtables lock; waiting (1s) for it to exit...\nAnother app is currently holding the xtables lock; waiting (3s) for it to exit...\nAnother app is currently holding the xtables lock; waiting (5s) for it to exit...\nAnother app is currently holding the xtables lock; waiting (7s) for it to exit...\nAnother app is currently holding the xtables lock; waiting (9s) for it to exit...\nAnother app is currently holding the xtables lock; waiting (11s) for it to exit...'

**root@ci:/tmp# docker-compose --version
docker-compose version 1.24.0, build 0aa5906**

```
common.yaml

version: '2'
services:
  agent:
      image: xxxxx
      privileged: true
      stdin_open: true
      tty: true
      cap_add:
        - ALL
      security_opt:
        - seccomp:unconfined

xx.yml

version: '2'

services:
  udp-1:
    container_name: udp-1
    hostname: udp1
    networks:
      quick_net:
        ipv4_address: 10.20.30.1
    ports:
      - "8722:8722"
      - "8708:5708"
      - "8709:5709"
      - "8799:5799"
      - "8713:5713"
      - "8715:5715"
    extends:
      file: common.yaml
      service: agent

  udp-2:
    container_name: udp-2
    hostname: udp2
    networks:
      quick_net:
        ipv4_address: 10.20.30.2
    extends:
      file: common.yaml
      service: agent

  udp-3:
    container_name: udp-3
    hostname: udp3
    networks:
      quick_net:
        ipv4_address: 10.20.30.3
    extends:
      file: common.yaml
      service: agent

  udp-4:
    container_name: udp-4
    hostname: udp4
    networks:
      quick_net:
        ipv4_address: 10.20.30.4
    extends:
      file: common.yaml
      service: agent

  udp-5:
    container_name: udp-5
    hostname: udp5
    networks:
      quick_net:
        ipv4_address: 10.20.30.5
    extends:
      file: common.yaml
      service: agent

  udp-6:
    container_name: udp-6
    hostname: udp6
    networks:
      quick_net:
        ipv4_address: 10.20.30.6
    extends:
      file: common.yaml
      service: agent

  udp-7:
    container_name: udp-7
    hostname: udp7
    networks:
      quick_net:
        ipv4_address: 10.20.30.7
    extends:
      file: common.yaml
      service: agent

  udp-8:
    container_name: udp-8
    hostname: udp8
    networks:
      quick_net:
        ipv4_address: 10.20.30.8
    extends:
      file: common.yaml
      service: agent

  udp-9:
    container_name: udp-9
    hostname: udp9
    networks:
      quick_net:
        ipv4_address: 10.20.30.9
    extends:
      file: common.yaml
      service: agent

  udp-10:
    container_name: udp-10
    hostname: udp10
    networks:
      quick_net:
        ipv4_address: 10.20.30.10
    extends:
      file: common.yaml
      service: agent

  udp-11:
    container_name: udp-11
    hostname: udp11
    networks:
      quick_net:
        ipv4_address: 10.20.30.11
    extends:
      file: common.yaml
      service: agent

  udp-12:
    container_name: udp-12
    hostname: udp12
    networks:
      quick_net:
        ipv4_address: 10.20.30.12
    extends:
      file: common.yaml
      service: agent

  udp-13:
    container_name: udp-13
    hostname: udp13
    networks:
      quick_net:
        ipv4_address: 10.20.30.13
    extends:
      file: common.yaml
      service: agent

  udp-14:
    container_name: udp-14
    hostname: udp14
    networks:
      quick_net:
        ipv4_address: 10.20.30.14
    extends:
      file: common.yaml
      service: agent

  udp-15:
    container_name: udp-15
    hostname: udp15
    networks:
      quick_net:
        ipv4_address: 10.20.30.15
    extends:
      file: common.yaml
      service: agent

  udp-16:
    container_name: udp-16
    hostname: udp16
    networks:
      quick_net:
        ipv4_address: 10.20.30.16
    extends:
      file: common.yaml
      service: agent

  udp-17:
    container_name: udp-17
    hostname: udp17
    networks:
      quick_net:
        ipv4_address: 10.20.30.17
    extends:
      file: common.yaml
      service: agent

  udp-18:
    container_name: udp-18
    hostname: udp18
    networks:
      quick_net:
        ipv4_address: 10.20.30.18
    extends:
      file: common.yaml
      service: agent

  udp-19:
    container_name: udp-19
    hostname: udp19
    networks:
      quick_net:
        ipv4_address: 10.20.30.19
    extends:
      file: common.yaml
      service: agent

networks:
  quick_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
          gateway: 10.20.30.254

```
