### ISSUE TITLE
restore fails with 9.2.7

### ISSUE THREAD

**Issue by blackmatch** [sameersbn/docker-gitlab#1956]
hello everyone, I need to restore gitlab to another server. I use docker-compose to run gitlab.

I run 

```shell
docker-compose run --rm gitlab app:rake gitlab:backup:restore
```

this command to restore gitlab on another server.

but i got the error:

```txt
-bash-4.2$ docker-compose run --rm gitlab app:rake gitlab:backup:restore
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...

date: invalid date '@1560446070_2019_06_13_9.2.7'
‣ 1560446070_2019_06_13_9.2.7_gitlab_backup.tar (created at )

Select a backup to restore: 1560446070_2019_06_13_9.2.7_gitlab_backup.tar
Running raketask gitlab:backup:restore...
Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml.
Unpacking backup ... tar: Skipping to next header
tar: Skipping to next header
tar: Archive contains '\312\255 \253\256\243^t9\\\232\022' where numeric off_t value expected
tar: Exiting with failure status due to previous errors
unpacking backup failed
```

and my docker-compose.yml looks like this:

```yml
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /opt/git/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.4-24
    ports:
    - "5433:5432"
    volumes:
    - /opt/git/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.2.7
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes:
    - /opt/git/gitlab/gitlab:/home/git/data:Z
    environment:
    - DEBUG=false
    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00
    ...
```

anyone can help me plz?
