### ISSUE TITLE
Using kubernetes config files doesn't working to deploy minikube

### ISSUE THREAD

**Issue by davidlandais** [sameersbn/docker-gitlab#2062]
I'm trying to deploy gitlab-ce using your provided .yml in /kubernetes.
Redis and Postgre are well deployed but gitlab seems to be unable to dial on tcp. for the readinessProbe. I'm a beginner to minikube. It seems that it can't provide LoadBalancer Service, so I tried with a Cluster IP and an Ingress. Unfornately this doesn't work too :/

**Does anyone already achieved to deploy on minikube ?**

gitlab-rc.yml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    name: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:12.5.2
        env:
        - name: TZ
          value: Europe/Berlin
        - name: GITLAB_TIMEZONE
          value: Berlin

        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: long-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: long-and-random-alpha-numeric-string

        - name: GITLAB_ROOT_PASSWORD
          value: Aw3s0mePassw0rd
        - name: GITLAB_ROOT_EMAIL
          value: admin@minikube.local

        - name: GITLAB_HOST
          value: gitlab.minikube.local
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "false"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: disable

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: gitlab
        - name: DB_NAME
          value: gitlab

        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "false"

        - name: IMAP_ENABLED
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
      - name: data
        emptyDir: {}
```

gitlab-svc.yml
```
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    name: gitlab
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    name: gitlab
```

Other files are not updated from the kubernetes directory.
