### ISSUE TITLE
Postgres update as preparation of gitlab 13.0.0

### ISSUE THREAD

**Issue by martinspaeth** [sameersbn/docker-gitlab#2157]
We are using the setup described here since a while. 

The migration went pretty smooth over the years. With the deprecation of Postgres < 11 introduced in Gitlab 13 I was wondering how i can prepare the migration to the new gitlab 13.0 in respect of our old postgres installation. 

We use the following Postgres image: 
sameersbn/postgresql:9.6-2

Thank you for your support and all the effort you put into this repo!

**Comment by solidnerd** [comment]
Hey @martinspaeth,
there was a discussion about how to migrate you can check this out: https://github.com/sameersbn/docker-gitlab/pull/2154#issuecomment-633497099

**Comment by MatthiasHertel** [comment]
@martinspaeth 
hi i have exacatly the same problem and i am unsure with @solidnerd  hint to the discussion in #2154 

my current setup is: (gitlab 12.10.6)

```
...
postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    - gitlab_network
  gitlab:
    restart: always
    image: sameersbn/gitlab:latest
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "22:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    - /srv/docker/certs:/certs
```

i am unsure how to upgrade this setup ... should i version pin the postgres service to 11.2 and then run a docker-compose pull and recreate ? there are two major version bumbs in the postgres service ....

thank u for help!
