### ISSUE TITLE
Mail sending does not work for me

### ISSUE THREAD

**Issue by sajt** [sameersbn/docker-gitlab#221]
I am very new to docker fig and gitlab. I made a docker-gitlab on my ubuntu server. Everything looks like fine, but whene I made a new user the system does not send any e-mail.
This is my latest fig.yml:

```
mysql:
  image: sameersbn/mysql:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - DB_NAME=gitlabhq_production
    - DB_HOST=192.168.0.2
gitlab:
  image: sajt/gitlab:latest
  links:
   - redis:redisio
   - mysql:mysql
  ports:
   - "10080:80"
   - "10022:22"
   - "443:443"
  environment:
   - GITLAB_SSH_PORT=10022
   - GITLAB_PORT=443
   - GITLAB_HTTPS=true
   - SSL_SELF_SIGNED=true
   - GITLAB_HTTPS_HSTS_MAXAGE=2592000
   - SMTP_USER=myemailaddress@gmail.com
   - SMTP_PASS=mypassword
   - SMTP_STARTTLS=true
   - SMTP_AUTHENTICATION=plain
  volumes:
   - /opt/gitlab/data:/home/git/data
redis:
  image: sameersbn/redis:latest
  environment:
    - REDIS_HOST=192.168.0.2
    - REDIS_PORT=6379
```

I disabled the ubuntu firewall.

When I creating the new user this is in the production log

```
Emails disabled! Interceptor prevented sending mail Account was created for you

Sent mail to email@gmail.com (58.2ms)
```

Thank you for the solution :)
