### ISSUE TITLE
Migration problem persists from 13.0 -> 13.3.4

### ISSUE THREAD

**Issue by aguedeney** [sameersbn/docker-gitlab#2227]
I've been trying to migrate to latest since 13.0 and I still get the following error with latest 13.3.4.

Anyone with a solution?

gitlab        | PG::InsufficientPrivilege: ERROR:  permission denied to create extension "btree_gist"

**Comment by aguedeney** [comment]
Ok, the following solved the problem after reading similar/same problem in issues:

DB_EXTENSION=pg_trgm,btree_gist

```
  postgresql:
    restart: always
    image: sameersbn/postgresql:11-20200524
    container_name: postgresql
    volumes:
    -  ...
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist
```
