### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by ysicing** [sameersbn/docker-gitlab#2267]
It looks like HTTPS doesn't work.

```
  gitlab:
    restart: always
    container_name: gitlab
    image: registry-vpc.cn-beijing.aliyuncs.com/k0s/gitlab:13.6.2
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "443:443"
    - "22:22"
    volumes:
    - /data/gitlab/data/gitlab:/home/git/data:Z
    - /data/gitlab/data/gitlabbackup:/home/git/backupdata:Z
    - /data/gitlab/data/certs:/home/git/data/certs:Z

    environment:
    - GITLAB_HTTPS=true
    - SSL_KEY_PATH=/home/git/data/certs/gitlab.key
    - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab.crt
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=code-in.xxx.com
    - GITLAB_PORT=443

/data/gitlab/data/certs# ls -alh
total 9.0K
drwxr-xr-x 2 root root 4.0K Dec 14 22:25 .
drwxr-xr-x 7 root root 4.0K Dec 14 23:43 ..
-rw-r--r-- 1 root root 4.0K Dec 14 15:29 gitlab.crt
-r-------- 1 root root 1.7K Dec 14 15:29 gitlab.key
```
And gitlab startup times the following error: 

rehash: warning: skipping gitlab.pem,it does not contain exactly one certificate or CRL
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
SSL Key, SSL Certificate were not found.

Can someone help me?
