### ISSUE TITLE
Modified `gitlab.yml` but not in effect

### ISSUE THREAD

**Issue by tonyjia87** [sameersbn/docker-gitlab#2287]
gitlab.yml

```
  monitoring:
    # Time between sampling of unicorn socket metrics, in seconds
    unicorn_sampler_interval: 10
    # IP whitelist to access monitoring endpoints
    ip_whitelist:
      - 0.0.0.0/8
    # Sidekiq exporter is webserver built in to Sidekiq to expose Prometheus metrics
    sidekiq_exporter:
      enabled: true
      address: 0.0.0.0
      port: 3807

```

restart docker ,but no effection. gitlab is work.
