### ISSUE TITLE
several "readv() failed" in nginx/gitlab_error.log

### ISSUE THREAD

**Issue by kumm** [sameersbn/docker-gitlab#229]
Of course in these cases the page does not load. But after a page reload some of them magically start to work without any error.

A few example for this:
```
2015/01/02 12:01:37 [alert] 319#0: *4 readv() failed (13: Permission denied) while reading upstream, client: 192.168.57.57, server: gitlab.wcs.local, request: "GET / HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/", host: "gitlab.wcs.local", referrer: "http://gitlab.wcs.local/"
2015/01/02 12:11:57 [alert] 288#0: *79 readv() failed (13: Permission denied) while reading upstream, client: 192.168.57.57, server: gitlab.wcs.local, request: "GET /help/workflow/notifications.md HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/help/workflow/notifications.md", host: "gitlab.wcs.local", referrer: "http://gitlab.wcs.local/help/workflow/README.md"
```

I have a lot of permanent errors too. They all refer to images. Some example:
```
2015/01/02 12:08:06 [alert] 288#0: *44 readv() failed (13: Permission denied) while reading upstream, client: 192.168.57.57, server: gitlab.wcs.local, request: "GET /help/workflow/ci_mr.png HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/help/workflow/ci_mr.png", host: "gitlab.wcs.local", referrer: "http://gitlab.wcs.local/help/workflow/gitlab_flow.md"
2015/01/02 12:08:06 [alert] 288#0: *60 readv() failed (13: Permission denied) while reading upstream, client: 192.168.57.57, server: gitlab.wcs.local, request: "GET /help/workflow/git_pull.png HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/help/workflow/git_pull.png", host: "gitlab.wcs.local", referrer: "http://gitlab.wcs.local/help/workflow/gitlab_flow.md"
2015/01/02 12:08:06 [alert] 288#0: *69 readv() failed (13: Permission denied) while reading upstream, client: 192.168.57.57, server: gitlab.wcs.local, request: "GET /help/workflow/messy_flow.png HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/help/workflow/messy_flow.png", host: "gitlab.wcs.local", referrer: "http://gitlab.wcs.local/help/workflow/gitlab_flow.md"
```
I've checked the file permissions inside the container, but can't find any problem. All failing files owned by "git.git" .

My fig.yml file:
```
gitlab:
  image: sameersbn/gitlab:7.6.2
  hostname: gitlab
  domainname: wcs.local
  environment:
    - DB_NAME=gitlab
    - DB_USER=gitlab
    - DB_PASS=****
    - GITLAB_HOST=gitlab.wcs.local
    - GITLAB_TIMEZONE=Budapest
    - GITLAB_EMAIL=****
    - GITLAB_SIGNUP=true
    - SMTP_HOST=***
    - SMTP_PORT=25
    - SMTP_STARTTLS=false
    - SMTP_USER=****
    - SMTP_PASS=****
  volumes:
    - /mnt/data/gitlab/data:/home/git/data
    - /mnt/data/gitlab/log:/var/log/gitlab
  links:
    - redis:redisio
    - postgresql:postgresql

redis:
  image: redis:2.8
  volumes:
    - /mnt/data/gitlab/redis:/data

postgresql:
  image: postgres:9.3
  environment:
   - POSTGRES_USER=gitlab
   - POSTGRES_PASSWORD=****
  volumes:
   - /mnt/data/gitlab/postgres:/var/lib/postgresql/data
```

I've assigned the hostname in my dns to the container's ip address, and i connect to it's web port directly.

docker info, and version
```
# docker info
Containers: 4
Images: 108
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.16.0-28-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 1001 MiB
Name: docker
ID: IQVJ:ATHQ:TDHX:AZWB:6XYU:MT2C:RJNN:6ZHY:GY6Y:OK3W:APRA:2A77
WARNING: No swap limit support
# docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

Any ideas what can I check?

**Comment by sameersbn** [comment]
These look like selinux issues. Please check your selinux configuration. 
A quick google search should allow you to fix this issue.

**Comment by sameersbn** [comment]
@kumm sorry about my earlier reply. this might not be related to selinux. Here gitlab is basically starting up. You should allow it some time to get ready to server requests.

**Comment by kumm** [comment]
Thanks for your reply!
I'm sure too this is not selinux. On ubuntu apparmor is the app-security beast. But according to audit logs there are no violations.

Sadly time does not help, i still getting the same errors. Every time i open "/help/workflow/gitlab_flow.md" every image cause an error in the log. But everything works - except i can't see these images. Weird... 

Still trying to figure out what is happening here. Previously I've started fig as a normal user with docker group membership. Now trying with root, but still the same.

**Comment by sameersbn** [comment]
@kumm I used the following `fig.yml` file, added a entry in `/etc/hosts` for the `gitlab.wcs.local` domain pointing to the container ip address and had no issues accessing http://gitlab.wcs.local

```yaml
gitlab:
  image: sameersbn/gitlab:latest
  hostname: gitlab
  domainname: wcs.local
  environment:
    - DB_NAME=gitlabhq_production
    - DB_USER=gitlab
    - DB_PASS=secretpass
    - GITLAB_HOST=gitlab.wcs.local
    - GITLAB_TIMEZONE=Budapest
    - GITLAB_SIGNUP=true
  volumes:
    - /tmp/gitlab/data:/home/git/data
    - /tmp/gitlab/log:/var/log/gitlab
  links:
    - redis:redisio
    - postgresql:postgresql

redis:
  image: sameersbn/redis:latest
  volumes:
    - /mnt/data/gitlab/redis:/data

postgresql:
  image: sameersbn/postgresql:latest
  environment:
   - DB_NAME=gitlabhq_production
   - DB_USER=gitlab
   - DB_PASS=secretpass
  volumes:
   - /tmp/gitlab/postgres:/var/lib/postgresql/data
```
