### ISSUE TITLE
Pages service does not start after upgrading from 13.12.4 to 14.0.0

### ISSUE THREAD

**Issue by Aoiujz** [sameersbn/docker-gitlab#2375]
Pages service does not start after upgrading from 13.12.4 to 14.0.0，then upgraded to 14.0.1 and the same problem occurred.

```
time="2021-06-28T01:01:42Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:42Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:42Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:43Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:43Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:43Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:45Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:45Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:45Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:48Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:48Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:48Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:27Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:27Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:27Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:28Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:28Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:28Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:30Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:30Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:30Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:34Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:34Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:34Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
```time="2021-06-28T01:01:42Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:42Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:42Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:43Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:43Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:43Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:45Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:45Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:45Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T01:01:48Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T01:01:48Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T01:01:48Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:27Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:27Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:27Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:28Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:28Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:28Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:30Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:30Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:30Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"
time="2021-06-28T02:28:34Z" level=info msg="GitLab Pages Daemon" revision=0e711de version=1.40.0
time="2021-06-28T02:28:34Z" level=info msg="URL: https://gitlab.com/gitlab-org/gitlab-pages"
time="2021-06-28T02:28:34Z" level=fatal msg="could not create domains config source" error="GitLab API URL or API secret has not been provided"

**Comment by lukas-runge** [comment]
Same issue for me:
![image](https://user-images.githubusercontent.com/21328241/123777037-1c07c300-d8d0-11eb-94d0-4f633a56f601.png)

I am having gitlab pages behind traefik so url is https but traffic behind traefik is http. Do I need to reconfigure something in `gitlab.rb` to have it working in 14.x.x? Till now this config worked fine for me:

```Ruby
pages_external_url "http://pages.service42.me"
gitlab_pages['inplace_chroot'] = true
gitlab_pages['access_control'] = true
```

Thanks already for helping out!
Kind regards,
@lukas-runge

**Comment by lukas-runge** [comment]
Same issue for me:
![image](https://user-images.githubusercontent.com/21328241/123777037-1c07c300-d8d0-11eb-94d0-4f633a56f601.png)

I am having gitlab pages behind traefik so url is https but traffic behind traefik is http. Do I need to reconfigure something in `gitlab.rb` to have it working in 14.x.x? Till now this config worked fine for me:

```Ruby
pages_external_url "http://pages.<domain>.<tld>"
gitlab_pages['inplace_chroot'] = true
gitlab_pages['access_control'] = true
```

Thanks already for helping out!
Kind regards,
@lukas-runge

**Comment by Aoiujz** [comment]
> Same issue for me:
> ![image](https://user-images.githubusercontent.com/21328241/123777037-1c07c300-d8d0-11eb-94d0-4f633a56f601.png)
> 
> I am having gitlab pages behind traefik so url is https but traffic behind traefik is http. Do I need to reconfigure something in `gitlab.rb` to have it working in 14.x.x? Till now this config worked fine for me:
> 
> ```ruby
> pages_external_url "http://pages.<domain>.<tld>"
> gitlab_pages['inplace_chroot'] = true
> gitlab_pages['access_control'] = true
> ```
> 
> Thanks already for helping out!
> Kind regards,
> @lukas-runge

Where is the `gitlab.rb`? Why can I only find the `gitlab.yml`

**Comment by kkimurak** [comment]
@Aoiujz  
FYI, `sameersbn/gitlab` is source-installed gitlab image, so you can only find `gitlab.yml` for configuration purpose. (For strictly, `gitlab.rb` is exist e.g. `/home/git/gitlab/lib/gitlab.rb` and so on. But this is not a file you're looking for...)

`gitlab.rb` is used for omnibus-installed gitlab to make easier to update `gitlab.yml` via  commands (`gitlab-ctl reconfigure`, for example). See https://docs.gitlab.com/omnibus/settings/gitlab.yml.html

Sorry for not helpful about "Pages service".

**Comment by lukas-runge** [comment]
Hey @Aoiujz,

for me just adding
```ruby
gitlab_pages['internal_gitlab_server'] = 'http://localhost:8080'
```
to the `gitlab.rb` config via the environment variable `GITLAB_OMNIBUS_CONFIG` provided by docker solved the actual issue which was accessing the api instead of `disk` of the gitlab instance.



<details>
<summary><b>full <code>docker-compose</code> config of running gitlab as docker service behind traefik</b></summary>

```yaml
version: "3.7"

services:
    gitlab:
        container_name: 'gitlab'
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'git.host.tld'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
              # Add any other gitlab.rb configuration here, each on its own line

              # Main Site
              external_url 'https://git.host.tld'
              nginx['listen_port'] = 80
              nginx['listen_https'] = false

              # SSH interaction with git
              gitlab_rails['gitlab_shell_ssh_port'] = 30022

              # GitLab Pages
              pages_external_url 'https://pages.host.tld/'
              pages_nginx['listen_port'] = 80
              pages_nginx['listen_https'] = false

              gitlab_pages['inplace_chroot'] = true
              gitlab_pages['access_control'] = true

              gitlab_pages['internal_gitlab_server'] = 'http://localhost:8080'

              # SMTP Settings
              gitlab_rails['gitlab_email_from'] = "noreply@host.tld"
              gitlab_rails['smtp_enable'] = true
              gitlab_rails['smtp_address'] = "mail.host.tld"
              gitlab_rails['smtp_port'] = 465
              gitlab_rails['smtp_user_name'] = "noreply@host.tld"
              gitlab_rails['smtp_password'] = "*********"
              gitlab_rails['smtp_domain'] = "mail.host.tld"
              gitlab_rails['smtp_authentication'] = "login"
              gitlab_rails['smtp_tls'] = true
              gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        ports:
        - '30022:22'
        volumes:
        - './config:/etc/gitlab:Z'
        - './logs:/var/log/gitlab:Z'
        - './data:/var/opt/gitlab:Z'
        - '/etc/localtime:/etc/localtime:ro'
        networks:
            - web
        labels:
            traefik.enable: "true"

            # GitLab
            traefik.http.services.gitlab.loadbalancer.server.port: "80"

            # git.host.tld
            traefik.http.routers.git-host-tld.rule: "HostRegexp(`git.host.tld`, `pages.host.tld`, `{subdomain:[a-z]+}.pages.host.tld`)"
            traefik.http.routers.git-host-tld.service: "gitlab"
            traefik.http.routers.git-host-tld.entrypoints: "https"
            traefik.http.routers.git-host-tld.tls.certresolver: "mydnsresolver"


networks:
    web:
        external: true
```

</details>

I finally found this information partly in the Docs, there is actually a migration guide you might also find helpful: https://docs.gitlab.com/ee/administration/pages/#migrate-gitlab-pages-to-140

Furthermore there is an official GitLab issue for feedback on the topic which actually also contains a lot of problems users faced when transitioning to 14.x.x and some great solutions such as the one that solved my issue in the end: https://gitlab.com/gitlab-org/gitlab/-/issues/331699

I hope you can get your deployment up in running. Best of luck! 🙌🚀🍀 

Kind regards,
@lukas-runge
