### ISSUE TITLE
GITLAB_PORT shows up in invitation emails link url

### ISSUE THREAD

**Issue by crud42** [sameersbn/docker-gitlab#2411]
Hi!
As i am currently in the process of updating some things :-)
We just activated smtp and noticed that the GITLAB_PORT is visible in the generated URL inside the user invitation email:

`https://gitlab.mydomain.com:10080/-/invites/YjxxcnrfNfws-sMBT6zrxxxxx`

inside docker-compose.yml its properly configured:

```
gitlab:
  ports:
    - "10080:80" 

  environment:
    - GITLAB_PORT=10080
```

but it looks like the port is rendered into the link. I remember that also happend with some links inside gitlab, too.

Any why this is happening?

Many thanks and best,
Chris
