### ISSUE TITLE
external redis in sentinel mode

### ISSUE THREAD

**Issue by yanliangchao** [sameersbn/docker-gitlab#2419]
What should I do if I want to connect the external redis in sentinel mode

**Comment by kkimurak** [comment]
Did you read official documentation? It will provides you most enough information: https://docs.gitlab.com/ee/administration/redis/replication_and_failover_external.html#example-configuration-of-the-gitlab-application

----

I don't know your environment - how many sentinels, how to set up them and so on - so I focus on gitlab-side configurations.
Currently `sameersbn/docker-gitlab` does not provide such feature, so you need to add it by yourself.  

In the document presented above, it is said that `config/resque.yml` is required - luckily, it exists as template file (`assets/runtime/config/gitlabhq/resque.yml`). In `config/resque.yml`, you can see that required configurations are commented out. 

Here are some idea to support the feature (note that I've never tested them excluding shell script behavior): 

1. Following the style of this project, adding configuration parameter is one of choise, Edit `resque.yml` like

    ```yaml
    production:
    # Redis (single instance)
    url: redis://{{REDIS_HOST}}:{{REDIS_PORT}}/{{REDIS_DB_NUMBER}}
    ##
    # comments are omitted..
    ##
    sentinels:
      -
        host: {{REDIS_SENTINELS_REPLICA_HOST}}
        port: {{REDIS_SENTINELS_REPLICA_PORT}} # point to sentinel, not to redis port
   ```

   Then add new parameter names to [`update_template ${GITLAB_RESQUE_CONFIG}` in `assets/runtime/functions`](https://github.com/sameersbn/docker-gitlab/blob/3dca21637494b737a96687e89449b903b7c15ac4/assets/runtime/functions#L230-L233) (in this case, add `REDIS_SENTINELS_REPLICA_HOST` and `REDIS_SENTINELS_REPLICA_PORT`. parameter names are just an example).

2. Edit `resque.yml` installation method in `assets/runtime/functions`
   method 1 is really simple, but contains some problems : cannot set multiple replica, unknown side effect may happen for users who don't need sentinels, and so on...  
   Here is an example to support multiple sentinels.  

    ```sh
    # assets/runtime/function L224-
    gitlab_configure_redis() {
      echo -n "Configuring gitlab::redis"

      gitlab_finalize_redis_parameters
      gitlab_check_redis_connection

      update_template ${GITLAB_RESQUE_CONFIG} \
        REDIS_HOST \
        REDIS_PORT \
        REDIS_DB_NUMBER

      # check if sentinels, then extract comma separated list
      if [[ -n ${REDIS_SENTINELS_REPLICA_HOSTS} ]]; then
        echo "  sentinels:" >> ${GITLAB_RESQUE_CONFIG}
        IFS_ORG=$IFS
        IFS=","
        for REPLICA_HOST in ${REDIS_SENTINELS_REPLICA_HOSTS}; do
          {
            printf "    -\n"
            printf "      host: %s\n" "${REPLICA_HOST}"
            printf "      port: 26379\n"
          } | cat >> ${GITLAB_RESQUE_CONFIG}
        done
        IFS=$IFS_ORG
      fi
    ```

    in this example ${REDIS_SENTINELS_REPLICA_HOSTS} is comma separated list. When `docker-compose.yml` is 

    ```yaml
    version 2.3

    # (omitted)
    gitlab:
    #(omitted)
      environment:
      - REDIS_SENTINELS_REPLICA_HOSTS=example,10.0.2.100
    ```

    following lines will be added to `resque.yml`

    ```yaml
    sentinels:
      -
        host: example
        port: 26379
      -
        host:  10.0.2.100
        port: 26379
    ```

For both case, you can set default values in `assets/runtime/env-default`. It'd be nice to add descriptions for them to README.md.  

After those modification, build image by yourself and check if that they works. Also, 

best,
