### ISSUE TITLE
Can't open background jobs / logs page in Admin

### ISSUE THREAD

**Issue by siuying** [sameersbn/docker-gitlab#246]
Tried to installation with latest version and restored data. I found that under "Admin area", I cannot open "Logs" (/admin/logs) or "Background Jobs" page (/admin/background_jobs)

I noticed that even I have set volume "/opt/gitlab/log:/var/log/gitlab", the folder /opt/gitlab/log contains empty directories ``gitlab``,  ``gitlab-shell``, ``nginx``, ``supervisor``. The server can be started normally but it seems the log is not written.

I used fig to manage my app, the gitlab section is something like this:

```
gitlab:
  image: sameersbn/gitlab:7.7.2
  environment:
    - RAILS_ENV=production
... (other config) ...
  links:
   - redis:redisio
   - postgresql:postgresql
  ports:
   - "80:80"
   - "22:22"
  volumes:
    - /opt/gitlab/data:/home/git/data
    - /opt/gitlab/log:/var/log/gitlab
```
