### ISSUE TITLE
Upgrading from 7 to 14 !

### ISSUE THREAD

**Issue by Glideh** [sameersbn/docker-gitlab#2466]
I know that's quite old but I'm currently starting from a `sameersbn/gitlab:7.14.1` alongside with a `sameersbn/postgresql:9.4-3`, and I'd like to push it to the most recent versions possible.

It seems to be suggested to pass through each major intermediate versions, so I successfully upgraded gitlab to `8.0.5-1`
_Changing `gitlab`'s version on my `docker-compose.yml`, stop/rm/up `gitlab`_

But I'm stuck with `9.X`, `gitlab` tells me:

> You must enable the pg_trgm extension

`postgresql` tells:

> permission denied to create extension "pg_trgm"
> Must be superuser to create this extension.

But I already have the extension enabled from the start:

```yml
//...
  db:
    image: sameersbn/postgresql:9.4-3
    environment:
    - DB_EXTENSION=pg_trgm,btree_gist
//...
  gitlab:
    image: sameersbn/gitlab:9.5.5
//...
```

Am I doing the right thing ?
Can someone point me the correct way to go ?

**Comment by nixel2007** [comment]
DB_EXTENSION works only on db creation. you need to login to pg as superuser and create this extension in the db manually

**Comment by Glideh** [comment]
Thanks for your answer, this extension is enabled from the start when I created the `db` container, but I actually restored a backup that was created from a db where `pg_trgm` was not enabled, maybe that's the issue. I'll try to enable it manually.

That said, do you think I'm proceeding well for the update ?
Is there a list of intermediate versions I must migrate somewhere ?

**Comment by nixel2007** [comment]
> Is there a list of intermediate versions I must migrate somewhere ?

You should check this page https://docs.gitlab.com/ee/update/#upgrade-paths

**Comment by Glideh** [comment]
That's interesting, thanks

**Comment by Glideh** [comment]
I achieved to reach the version 14.0.0 !
For those interested by migrating gitlab from 7 to 14 & Postgres from 9 to 12, here are the migration steps I used:

My original `docker-compose.yml` extract:

```yml
#...
  db:
    image: sameersbn/postgresql:9.4-3
    environment:
    - DB_NAME=gitlab
    - DB_EXTENSION=pg_trgm,btree_gist
#...
  gitlab:
    image: sameersbn/gitlab:7.14.1
    environment:
    - DEBUG=true # Can be useful to check what is going wrong if needed
#...
```

- If the database is as **old** as mine was, `pg_trgm` & `btree_gist` extensions might not be enabled, so we need to do them manually. So enter the **postgres client**:
```
docker-compose exec db sudo -u postgres psql
```
* Then **enable the extensions**
```sql
psql> \c gitlab # Specifies the database on which we are enabling the extensions, change the name accordingly
gitlab> CREATE EXTENSION pg_trgm;
gitlab> CREATE EXTENSION btree_gist;
```

- When using `sameersbn/postgresql` the **migration** is really easy, we just need to **change** the `db` **version** to `12-20200524` in `docker-compose.yml` then:

```
docker-compose stop db
docker-compose rm -f db
docker-compose up db
```

- Make sure the migration goes well (it did for me)
- About gitlab, the first version **must** be `8.0.5-1` (as [stated on the doc](https://github.com/sameersbn/docker-gitlab#upgrading))
- After that I used this migration path successfully:
  - 7.14.1
  - 8.0.5-1
  - 9.5.5
  - 10.8.4
  - 11.11.0
  - 12.10.6-1
  - 13.12.4
  - 14.0.0
- In order to migrate `gitlab`, **same way** as postgresql, **change the version** on `docker-compose.yml` then for **each one**:
```
docker-compose stop gitlab
docker-compose rm -f gitlab
docker-compose up gitlab
```
- Make sure the migration goes well on the log
