### ISSUE TITLE
PlantUML Integration

### ISSUE THREAD

**Issue by Basti-Fantasti** [sameersbn/docker-gitlab#2515]
Hi @all 

I've added the plantuml server as suggested in the gitlab docs to my docker-compose file.
I can also open the plantuml server interface directly on port 8080 on my server.

but how can I hand over this configuration in my docker-compose.yml file?
It always throws an error:

````yaml

environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['custom_gitlab_server_config'] = "location /-/plantuml/ { \n    proxy_cache off; \n    proxy_pass  http://plantuml:8080/; \n}\n"

````

I'm using the standard yaml docker-compose file without the omnibus configuration from this repository root folder.

Thanks in advance
