### ISSUE TITLE
public key invalid after the docker gitlab recreate

### ISSUE THREAD

**Issue by stardustman** [sameersbn/docker-gitlab#2521]
hello, I have config the mirror repository  of a gitlab's repository for syncing change to github's repo, the protocol I use is ssh, I have add the mirror repository's public key to the github repository's deploy key list.
but when I recreate the gitlab docker container, it seems the public key not work?
how to fix?

**Comment by kkimurak** [comment]
When container is up, public keys are regenerated so your deploy keys will be expired. To persist it, specify data directory as volumes:

```yaml
# in docker-compose.yml
services:
  gitlab:
    image: sameersbn/gitlab:14.8.2
    volumes:
    - ./gitlab_data:/home/git/data:Z
```

You can find ssh public keys in `gitlab_data/ssh/` on host machine.  
Check [how `sameersbn/gitlab` generates host key](https://github.com/sameersbn/docker-gitlab/blob/739480e81d20b3fc5f3f5a721fde1a4a4041de44/assets/runtime/functions#L1620-L1635). `GITLAB_DATA_DIR` (/home/git/data) is defined in [Dockerfile](https://github.com/sameersbn/docker-gitlab/blob/739480e81d20b3fc5f3f5a721fde1a4a4041de44/Dockerfile#L83).
