### ISSUE TITLE
Performance issue, slow page loading on "project1/-/issues/1" page on GitLab 14.10.2 fresh install

### ISSUE THREAD

**Issue by stephane-klein** [sameersbn/docker-gitlab#2566]
Hi,

I run a fresh, empty GitLab `sameersbn/gitlab:14.10.2` instance on this host: 

- [Intel® NUC 11 Performance kit - NUC11PAHi7](https://www.intel.com/content/www/us/en/products/sku/205073/intel-nuc-11-performance-kit-nuc11pahi7/specifications.html)
  - [Intel® Core™ i7-1165G7 Processor (12M Cache, up to 4.70 GHz)](https://www.intel.com/content/www/us/en/products/sku/208662/intel-core-i71165g7-processor-12m-cache-up-to-4-70-ghz/specifications.html)
  - [Crucial 32GB Kit (2 x 16GB) DDR4-3200 SODIMM CT2K16G4SFRA32A](https://www.crucial.com/memory/ddr4/ct2k16g4sfra32a)
  - [WD_BLACK™ SN850 NVMe™ SSD - 1To](https://www.westerndigital.com/fr-fr/products/internal-drives/wd-black-sn850-nvme-ssd#WDS100T1X0E)

I use this `docker-compose.yml` configuration:

```
version: '3.9'
services:
  postgres:
    image: index.docker.io/postgres:12.4-alpine
    command: >
      -c shared_buffers=2000MB
      -c maintenance_work_mem=150MB
      -c work_mem=50MB
      -c seq_page_cost=0.8
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: gitlab
      POSTGRES_DB: gitlabhq_production
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data

...

  gitlab:
    image: sameersbn/gitlab:14.10.2
    ports:
      - "9922:22"
      - 80:80
    environment:
      ....
      PUMA_WORKERS: 32
      PUMA_THREADS_MIN: 1
      PUMA_THREADS_MAX: 16
      PUMA_PER_WORKER_MAX_MEMORY_MB: 8048
      PUMA_MASTER_MAX_MEMORY_MB: 8048
      ...
```

I created empty issue: `http://127.0.0.1/gitlab-instance-71f415c6/project1/-/issues/1`

Here is the performance of `http://127.0.0.1/gitlab-instance-71f415c6/project1/-/issues/1` page:

![Screenshot from 2022-05-22 12-17-11](https://user-images.githubusercontent.com/54498080/169690586-8dd8b89d-46a6-413b-afdd-d0e0fcaee8d3.png)

This page take `857ms`, sometime`1070ms`. `3800ms` if I count all page dependencies loading.

This is the `HAR` file [issue1.har](https://github.com/sameersbn/docker-gitlab/files/8749217/issue1.txt), I excluded `notes` and `realtime_changes` requests.

This is the [performance bar](https://docs.gitlab.com/ee/administration/monitoring/performance/performance_bar.html) flamegraph in wall mode  ([issues_1_perf_bar_1653215576325.json](https://github.com/sameersbn/docker-gitlab/files/8749224/issues_1_perf_bar_1653215576325.json.txt)) : ![Screenshot from 2022-05-22 12-31-34](https://user-images.githubusercontent.com/54498080/169691038-1335ca1e-a968-4145-8a3c-c569145191cd.png).

Do you have any idea why this page is so slow to load? Do you have a solution or is it a real GitLab implementation problem?
