### ISSUE TITLE
Strange behaviour with CI/CD

### ISSUE THREAD

**Issue by sam-brett** [sameersbn/docker-gitlab#2576]
Hello, 

I've recently upgraded from 13.7 through to 14.10.3 (taking a lot of steps along the way). All my projects are fine and everything seems stable with the exception of the CI/CD area. I can't say I'm massively experienced with the runners, but I have registered two runners successfully. However when I click on them in the Admin/Runners area a new page doesn't load, the same when I click the edit button. They show up as in contact "just now". 

When I assign a project to a runner, or use a shared runner, and try to run them I get "The scheduler failed to assign job to the runner, please try again or contact system administrator". The logs of the runner don't show anything, but I also don't get any errors in the logs. 

I'm also getting conflicting messages on the validity of my .gitlab-ci.yml, in the gitlab editor it says its valid, then on execution it isn't.

Any guidance would be appreciated. I don't have a huge amount on this server, so nuking it and restarting from scratch is an option. It feels like something is wrong at the backend, maybe with the jobs and runners tables?

<img width="1289" alt="Screenshot 2022-06-04 at 10 19 13" src="https://user-images.githubusercontent.com/64466838/171993034-8b4d2a74-3a88-4ac8-a2c9-e79b40138652.png">

``` yml
version: '3'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    restart: unless-stopped
```

``` toml
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "test"
  url = "redacted address"
  token = "bsxW8-TySKikXJnCDirt"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "gradle:jdk11-jammy"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
```

``` yml
image: gradle:jdk11-jammy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  tags:
    - test
 ```

<img width="491" alt="Screenshot 2022-06-04 at 10 41 12" src="https://user-images.githubusercontent.com/64466838/171993901-ed393a74-7a79-49a0-a729-c9428f42fc7f.png">
