### ISSUE TITLE
How to reload when renewing certificates

### ISSUE THREAD

**Issue by 3kami3** [sameersbn/docker-gitlab#2635]
I am using GitLab Container Registry with Let's encrypt.
I am looking for a way to reload the certificate when it is renewed.
Is there a better way than the following command?
```
docker compose -f /foo/docker-compose.yml restart
```
docker compose restart has a long downtime and I would like to know a faster way.

Omnibus GitLab seems to do it with the following command
https://docs.gitlab.com/omnibus/settings/ssl.html#renew-the-certificates-automatically
```
sudo gitlab-ctl reconfigure
```

My configuration: /foo/docker-compose.yml
```yaml
services:
  ...
  gitlab:
    restart: always
    image: sameersbn/gitlab:15.3.3
    ...
    volumes:
    - /etc/letsencrypt/live/example.com:/root/certs:ro
    - /etc/letsencrypt/archive:/archive:ro
    ...
    environment:
    - GITLAB_REGISTRY_CERT_PATH=/root/certs/fullchain.pem
    - GITLAB_REGISTRY_KEY_PATH=/root/certs/privkey.pem
    ...
  ...
  registry:
    restart: always
    image: registry:2.8.1
    ...
    volumes:
    - /etc/letsencrypt/live/example.com:/root/certs:ro
    - /etc/letsencrypt/archive:/archive:ro
    ...
    environment:
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/root/certs/fullchain.pem
    - REGISTRY_HTTP_TLS_CERTIFICATE=/root/certs/fullchain.pem
    - REGISTRY_HTTP_TLS_KEY=/root/certs/privkey.pem
    ...
```
