### ISSUE TITLE
full example of gitlab with container registry

### ISSUE THREAD

**Issue by mehranheydarian** [sameersbn/docker-gitlab#2638]
Does anyone have a complete Docker Compose of GitLab with container Registry to provide?

**Comment by mschadev** [comment]
my docker-compose.yml
```yml
version: '2.3'

services:
  registry:
    container_name: gitlab_registry
    image: registry
    restart: always
    expose:
      - "5000"
    ports:
      - "10500:5000"
    volumes:
      - /volume1/docker/gitlab-registry/registry:/registry
      - /volume1/docker/gitlab-registry/registry-certs:/certs
    environment:
      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
      - REGISTRY_AUTH_TOKEN_REALM=https://YOUR_DOMAIN.COM/jwt/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
      - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.crt
      - REGISTRY_STORAGE_DELETE_ENABLED=true

  gitlab:
    container_name: gitlab_web
    restart: always
    image: sameersbn/gitlab:15.5.3
   # ...
    volumes:
    - /volume1/docker/gitlab-registry/registry-certs:/certs
    environment:
    - GITLAB_REGISTRY_ENABLED=true
    - GITLAB_REGISTRY_HOST=YOUR_DOCKER_REGISTRY_DOMAIN.COM
    - GITLAB_REGISTRY_PORT=443
    - GITLAB_REGISTRY_API_URL=http://registry:5000
    - GITLAB_REGISTRY_KEY_PATH=/certs/registry.key
    # ...
```
