### ISSUE TITLE
Include builtin-kas in docker image provided by @kkimurak 

### ISSUE THREAD

**Issue by yougotborked** [sameersbn/docker-gitlab#2736]
I would like to request builtin-kas be added to the image. See the fork provided by @kkimurak 

---

As already reported above (https://github.com/sameersbn/docker-gitlab/pull/2598#issuecomment-1172864976), this image currently does not provides built-in KAS. This PR requires external KAS is exists.

If you have time to do that, could you please try to build and test my [`support-builtin-kas` branch](https://github.com/kkimurak/docker-gitlab/tree/support-builtin-kas) ?  
In addition to the work done by @antt1995, I've made sure to build gitlab-kas when building the image and add setting for supervisord to launch kas if enabled. Also I have added configuration file for KAS and minimal configuration parameters. 

I have never used Kubernetes so never tested if the registration success, but made sure the `gitlab-kas` service starts without exiting.  
Here are new entries for env of `docker-compose.yml` on test:

````yaml
services:
  gitlab:
    environment:
      GITLAB_KAS_ENABLED: 'true'
      # If we don't set this, built-in gitlab-kas will exit with an error
      # See https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/blob/8069d9b79763859b5bcead437a28f4dc73b66ae8/cmd/kas/kasapp/configured_app.go#L96-98
      OWN_PRIVATE_API_URL: grpc://127.0.0.1:8155
````

_Originally posted by @kkimurak in https://github.com/sameersbn/docker-gitlab/issues/2598#issuecomment-1225428725_
