### ISSUE TITLE
expose backup config "connection"

### ISSUE THREAD

**Issue by SIvaCoHan** [sameersbn/docker-gitlab#2795]
I want to use Aliyun fog plugin to backup.
But The config file only support GCE and AWS.

can you expose backup config to a variable ?

this line
https://github.com/sameersbn/docker-gitlab/blob/master/assets/runtime/config/gitlabhq/gitlab.yml#L1075

and what I what is here
https://gitlab.com/gitlab-org/gitlab/-/issues/372491

```
  backup:
    upload:
      connection:
        provider: aliyun
        aliyun_accesskey_id: *****
        aliyun_accesskey_secret: *****
        aliyun_oss_bucket: test-fog-aliyun
        aliyun_oss_endpoint: oss-us-east-1.aliyuncs.com
      remote_directory: test-fog-aliyun

```
