### ISSUE TITLE
[Question] How to change the clone link from localhost to my domain?

### ISSUE THREAD

**Issue by chenliu1993** [sameersbn/docker-gitlab#2902]

**Comment by kkimurak** [comment]
Set environment variable [`GITLAB_HOST`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_host) and [`GITLAB_PORT`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_port) for gitlab container. Here is an example for docker-compose.yml:

```yaml
version: '2.3'
services:
  gitlab:
    image: sameersbn/gitlab:latest
    depends_on:
    - redis
    - postgresql
    ports:
    - "12348:80"
    - "10022:22"
    environment:
    - GITLAB_HOST=gitlab.example.com
    - GITLAB_PORT=12348
```

These configuration will change the clone link to `gitlab.example.com:12348`.
