### ISSUE TITLE
Web log-in broken

### ISSUE THREAD

**Issue by djelenc** [sameersbn/docker-gitlab#2932]
I have an issue with web-login. We are using gitlab 16.10.1 and at some point, it has become impossible for users to to log-in via web. (If you believe this is a gitlab issue, please let me know and I'll try my luck upstream.)

Unfortunately, I cannot tell whether the issue began with this version of Gitlab or with some other prior to that.

I am sure, however, that the issue did not manifest at an upgrade, but at a later point. What I mean is that after the upgrade, I immediately checked the instance, and it worked. The issue came about only after existing login credentials expired and the web application required users to perform a fresh log in. Users cannot log in since.

When logging in, Gitlab web app always responds by saying credentials are invalid. However, we are certain the credentials are in fact valid:

-   I've reset a few users' passwords using rails console, but they are still unable to log in.
-   However, the users can access projects (e.g. git clone) using git over HTTPS with their usernames and passwords. In this case (the same) credentials are accepted as valid.

The issue seems to be related to the web application itself. I&rsquo;m looking at the logs, but I cannot see anything useful. (I&rsquo;ve checked basically every  log in `/var/log/gitlab/gitlab/*.log`, but I see no errors.)

Some more background:

-   We were using LDAP and basic Gitlab login to authenticate users, but the organization has since turned off the LDAP. (We are to switch to OIDC next, but this is not yet implemented in our gitlab instance.)
-   After the organization turned off the LDAP, users were able to login via web using their Gitlab credentials without problems.
-   Now, out of a sudden, this is no longer possible.
-   I am running an nginx reverse-proxy in front of this docker-compose setup.

Any idea will be greatly appreciated. Below I enclose my docker-compose config.

```yml
version: '2.3'

services:
  redis:
    restart: always
    image: redis:6.2
    command:
    - --loglevel warning
    volumes:
    - redis-data:/data:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:14-20230628
    volumes:
    - postgresql-data:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist

  gitlab:
    restart: always
    image: sameersbn/gitlab:16.10.1
    depends_on:
    - redis
    - postgresql
    ports:
    - "22:22"
    - "127.0.0.1:10080:80"
    volumes:
    - gitlab-data:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    environment:
    - DEBUG=false

    - GITLAB_PAGES_ENABLED=true
    - GITLAB_PAGES_HTTPS=true
    - GITLAB_PAGES_PORT=443
    - GITLAB_PAGES_DOMAIN=...
    - GITLAB_PAGES_ACCESS_CONTROL=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=...
    - GITLAB_TIMEZONE=...

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=...redacted...
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=22
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=...
    - GITLAB_SECRETS_SECRET_KEY_BASE=...
    - GITLAB_SECRETS_OTP_KEY_BASE=...

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=...
    - GITLAB_EMAIL_REPLY_TO=...
    - GITLAB_INCOMING_EMAIL_ADDRESS=...

    - GITLAB_BACKUP_SCHEDULE=weekly
    - GITLAB_BACKUP_TIME=04:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=...
    - SMTP_HOST=...
    - SMTP_PORT=...
    - SMTP_USER=
    - SMTP_PASS=
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false


    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_AUTO_LINK_USER=true
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=
    - OAUTH_BITBUCKET_URL=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_USERNAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=
    - OAUTH_AUTH0_SCOPE=

volumes:
  redis-data:
  postgresql-data:
  gitlab-data:
```
