### ISSUE TITLE
Configure Service Desk

### ISSUE THREAD

**Issue by thiagomdiniz** [sameersbn/docker-gitlab#2996]
How can we configure/enable Service Desk?

From what I understand this project does not support the `GITLAB_OMNIBUS_CONFIG` environment variable (I tried to [configure it through this variable](https://docs.gitlab.com/17.2/ee/user/project/service_desk/configure.html?tab=Docker) but it didn't work).

It was not clear how I could manually edit the configuration file to add the relevant settings.

I'm using Office 365 / Microsoft Graph.  
For example:
- https://docs.gitlab.com/17.2/ee/user/project/service_desk/configure.html?tab=Self-compiled+%28source%29#microsoft-graph

Thanks in advance!

**Comment by thiagomdiniz** [comment]
For example, could I add this Service Desk configuration manually by copying the `/etc/docker-gitlab/runtime/config/gitlabhq/gitlab.yml` file out of the container and mapping it as a volume?  
Would this be the correct/ideal way in this case?

**Comment by thiagomdiniz** [comment]
I managed to make the service desk work with Microsoft Graph.  
Here are the changes I made for reference.

I copied the configuration template file out of the container:
```
docker compose cp gitlab:/etc/docker-gitlab/runtime/config/gitlabhq/gitlab.yml .

```

In the `gitlab.yml` local file I modified the `incoming_email` section like this:
```
  incoming_email:
    enabled: {{GITLAB_INCOMING_EMAIL_ENABLED}}

    # The email address including the `%{key}` placeholder that will be replaced to reference the item being replied to.
    # The placeholder can be omitted but if present, it must appear in the "user" part of the address (before the `@`).
    # Please be aware that a placeholder is required for the Service Desk feature to work.
    email: "email@example.com"
    address: "{{GITLAB_INCOMING_EMAIL_ADDRESS}}"

    # Service Desk - Microsoft Graph custom config
    delete_after_delivery: false
    inbox_method: 'microsoft_graph'
    inbox_options:
      tenant_id: ''
      client_id: ''
      client_secret: ''
      poll_interval: 120


    # Email account username
    # With third party providers, this is usually the full email address.
    # With self-hosted email servers, this is usually the user part of the email address.
    user: "{{IMAP_USER}}"
    # Email account password
    #password: "{{IMAP_PASS}}"

    # IMAP server host
    #host: "{{IMAP_HOST}}"
    # IMAP server port
    #port: {{IMAP_PORT}}
    # Whether the IMAP server uses SSL
    #ssl: {{IMAP_SSL}}
    # Whether the IMAP server uses StartTLS
    #start_tls: {{IMAP_STARTTLS}}

    # The mailbox where incoming mail will end up. Usually "inbox".
    #mailbox: "{{IMAP_MAILBOX}}"

    # The IDLE command timeout.
    #idle_timeout: {{IMAP_TIMEOUT}}
    # The log file path for the structured log file.
    # Since `mail_room` is run independently of Rails, an absolute path is preferred.
    # The default is 'log/mail_room_json.log' relative to the root of the Rails app.
    #
    # log_path: log/mail_room_json.log

    # Whether to expunge (permanently remove) messages from the mailbox when they are deleted after delivery
    #expunge_deleted: false
```

I added these environment variables:
```
GITLAB_INCOMING_EMAIL_ENABLED=true
GITLAB_INCOMING_EMAIL_ADDRESS=email+%{key}@example.com
IMAP_USER=email@example.com
```

And in docker compose I mapped the local file as a volume:
```
     volumes:
       ...
       - "./gitlab.yml:/etc/docker-gitlab/runtime/config/gitlabhq/gitlab.yml"
```
