### ISSUE TITLE
How to configure the Container metadata registry database on this image？

### ISSUE THREAD

**Issue by HoshinoRei** [sameersbn/docker-gitlab#3044]
The configuration method in [Official Tutorial](https://docs.gitlab.com/17.6/ee/administration/packages/container_registry_metadata_database.html) does not apply to this image, how to configure the Container metadata registry database painlessly after using this image?

**Comment by kkimurak** [comment]
Set following configuration parameters in your configuration file (`environment` section in docker-compose.yml, `env` section in gitlab-rc.yml for example):

| official tutorial: entry in /etc/gitlab/gitlab.rb | configuration parameter for sameersbn/gitlab | 
| --- | --- | 
| registry['database'].enabled | [`GITLAB_REGISTRY_ENABLED`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_enabled) | 
| registry['database'].host    | [`GITLAB_REGISTRY_HOST`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_host) | 
| registry['database'].port    | [`GITLAB_REGISTRY_PORT`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_port) | 
| registry['database'].api_url | [`GITLAB_REGISTRY_API_URL`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_api_url) | 
| registry['database'].key     | [`GITLAB_REGISTRY_KEY_PATH`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_key_path) | 
| registry['database'].path    | [`GITLAB_REGISTRY_DIR`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_dir) | 
| registry['database'].issuer  | [`GITLAB_REGISTRY_ISSUER`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_issuer) | 

In the source-installed environment provided by this image (`sameersbn/gitlab`), settings must be written in `/home/git/gitlab/config/gitlab.yml` instead of `/etc/gitlab/gitlab.rb` that is used in omnibus-installation.  
sameersbn/gitlab provides a file that replaces the values ​​in this configuration file with placeholders. When the container is started, these placeholders are rewritten according to the values ​​of the environment variables.

optionally, internal certificates can be generated on startup if you set [`GITLAB_REGISTRY_GENERATE_INTERNAL_CERTIFICATES`](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#gitlab_registry_generate_internal_certificates) to true.

This is documented in README.md (use links on each configuration parameter)

Note that our configuration parameters are not up to date - some parameters may be slate, some upstream configurations may not have a corresponding parameter.  
For example, we have not been able to support user-password authentication yet (entry `registry['database'].user` and `.password` cannot be set).  

Please submit a pull request to update configuration files or wait for the update. To submit a PR, please refer to the merged pull request (#2953 for example).


Alternatively, you may be able to set these parameters by

1. launch container (`docker run`, `docker compose up` and so on)
2. log into container as user `git` (`docker exec -it -u git your-gitlab-container-name /bin/bash`)
3. edit `gitlab.yml` directly (note that most of major text editors are not available in container)
4. log out from container
5. log into container as user `root` (`docker exec -it your-gitlab-container-name /bin/bash`)
6. reload gitlab services by executing `supervisorctl reload`

**Comment by uda** [comment]
This is weird, the response from @kkimurak is out of place, mentions unrelated variables the environment variables are for the registry itself and the database config is just wrong, the entire text sounds like it was auto-generated, and not by a human

**Comment by kkimurak** [comment]
Um, @uda , sorry but you are half right. I was probably asleep when I wrote this, which means I was trying hard to explain how to configure the registry itself, not how to access the registry[“database”]. This doesn't answer the question and misses the point entirely.

I'll update my response as follows (though I'm only repeating the bottom half of my response above)

- Not supported at this time.
- Adding a new configuration parameter requires some changes.
- The procedure and the changes you need to make can be found in previous pull requests, for example, #2953.
- I don't use a registry so I'm not going to take the initiative to make this change  
  but I'm willing to make a preliminary change without checking if it will work on my local environment and have you guys review it to see if it will work.

----

> the entire text sounds like it was auto-generated, and not by a human

I've been 100% human for several years now when I first commented on an issue in this repository. But there is no way to prove it, and it is a meaningless question and answer.  

Personally, as a non-English speaker who lives in an island country like Japan using almost nothing but Japanese, I've had a lot of help from machine translation, and I'm sure that whatever “auto-generate” you're referring to is better at English than I am in most cases.

**Comment by uda** [comment]
Thanks for clarifying.

I verified that the last suggestion, of modifying the `yml` files don't survive the container restart, so the only solution for someone wanting the new metadata database is to implement it, wait for it to be implemented or migrate

**Comment by uda** [comment]
I managed to get this to work for me, my initial assumption was that this needs to happen inside the GitLab container, but this actually needs to happen in the registry container, so no need to wait for implementation from this project (though documentation about this can be added alongside the existing registry examples)

My docker-compose.yml for the registry was like this:

```yaml
  registry:
    image: "docker.io/library/registry:2.8.3"
    depends_on:
      - gitlab
      - redis
    # For exposing to nginx
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - registry-data:/var/lib/registry
      - gitlab-certs:/certs
      - /root/.acme.sh/REGISTRY_DOMAIN:/etc/ssl/REGISTRY_DOMAIN:ro
    env_file:
      - "/srv/gitlab/registry.env"
    restart: always
```

I changed it to this (GITLAB_VERSION is set in my `.env` file and corresponds the version used for the GitLab image):

```yaml
  registry:
    image: "registry.gitlab.com/gitlab-org/build/cng/gitlab-container-registry:v${GITLAB_VERSION}"
    depends_on:
      - gitlab
      - redis
      - postgres
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - registry-conf:/etc/docker/registry
      - registry-data:/var/lib/registry
      - gitlab-certs:/certs
      - /root/.acme.sh/REGISTRY_DOMAIN:/etc/ssl/REGISTRY_DOMAIN:ro
    env_file:
      - "/srv/gitlab/registry.env"
    restart: always
```

Now my `registry.env` didn't change, just the old `REGISTRY_*` env vars, but I had to add the config file at `/var/lib/docker/volumes/gitlab_registry-conf/_data/config.yml`:

```yaml
# This config file is a basic configuration using database metadata and
# filesystem blob storage.
version: 0.1
log:
  accesslog:
    disabled: false
    formatter: text
  level: info
  formatter: text
  fields:
    service: registry
storage:
  delete:
    enabled: true
  filesystem:
    # Temp dir, rename if you need persistence.
    # registry/storage/paths.go describes the structure of the data
    # written to this directory
    rootdirectory: "/tmp/registry"
database:
  enabled:  true
  host:     postgres
  port:     5432
  user:     "registry"
  password: "PASSWORD"
  dbname:   "registry"
  sslmode:  "disable"
http:
  # Registry API will be accessible at localhost:5000
  addr: :5000
  debug:
    addr: :5001
      # Metrics will be accessible at localhost:5001/metrics/
    prometheus:
      enabled: false
      path: /metrics
      # Profiling information will be accessible at localhost:5001/debug/pprof/
    pprof:
      enabled: false
```

Since this instance doesn't serve many people I went for the one step migration as described in the [documentation](https://docs.gitlab.com/administration/packages/container_registry_metadata_database/#one-step-import) (Replace `gitlab-ctl registry-database` with `registry database`), run this AFTER making the docker-compose.yml changes and the config file (the volume is created when you run `docker compose run` so you can edit the file from within docker or from the outside, but you need it there to run the migration and import)

```shell
docker compose pull
docker compose stop registry
docker compose run --rm -it registry bash
registry database migrate up
registry database import
exit
docker compose up -d
```

The import takes some time depending on the amount of images, but once up that's it, you have the gitlab registry running with registry metadata db
