### ISSUE TITLE
Can not start container

### ISSUE THREAD

**Issue by mikehaertl** [sameersbn/docker-gitlab#310]
I've tried to run a simple test setup, but failed. Here's the `docker-compose.yml` that I've used:

```
gitlab:
    image: sameersbn/gitlab:7.10.1
    links:
        - db
        - redis
    environment:
        DB_TYPE: mysql
        DB_HOST: db
        DB_NAME: gitlab
        DB_USER: gitlab
        DB_PASS: gitlab
        REDIS_HOST: redis
        REDIS_PORT: 6379
db:
    image: mysql:5.6.22
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gitlab
        MYSQL_USER: gitlab
        MYSQL_PASSWORD: gitlab
redis:
    image: redis:3.0.0
```

Sidenote: I don't know why you created your own mysql and redis images. I think the official images are just fine and should work. If that's an issue I think you should make them work.

When I run `docker-compose up` the redis and mysql containers start just fine. But the gitlab container throws this error message and then exits:

```
gitlab_1 | debconf: unable to initialize frontend: Dialog
gitlab_1 | debconf: (TERM is not set, so the dialog frontend is not usable.)
gitlab_1 | debconf: falling back to frontend: Readline
gitlab_1 | debconf: unable to initialize frontend: Readline
gitlab_1 | debconf: (This frontend requires a controlling tty.)
gitlab_1 | debconf: falling back to frontend: Teletype
gitlab_1 | Creating SSH2 RSA key; this may take some time ...
gitlab_1 | Creating SSH2 DSA key; this may take some time ...
gitlab_1 | Creating SSH2 ECDSA key; this may take some time ...
gitlab_1 | Creating SSH2 ED25519 key; this may take some time ...
gitlab_1 | invoke-rc.d: policy-rc.d denied execution of restart.
gitlab_1 | sed: -e expression #1, char 20: unknown option to `s'
gitlab_gitlab_1 exited with code 1
```

**Comment by diresi** [comment]
I've seen this once and IIRC the problem was some environment variable due to container links. Try linking redis as redisio (although I don't know how to do that using docker-compose).

**Comment by mikehaertl** [comment]
Hmm, not sure why that would make a difference, but I've tried. With `docker-compose` you just have to change the name of the container. So I've modified it from `redis` to `redisio`. No difference.

**Comment by diresi** [comment]
OK, sorry.
I suggested this due to the /app/init script, where the image env vars collided with env vars from docker container links.
Maybe you can track down your problem in an interactive bash session. Insert `set -x` somewhere at the top of `/app/init` and run it manually with `/app/init app:start`. Then you should see the line where the script fails.

**Comment by mikehaertl** [comment]
Ok, added `set -x`. The lines where it fails are:

```
...
 '[' mysql == mysql ']'
+ sudo -u git -H sed 's/{{DB_ADAPTER}}/mysql2/' -i config/database.yml
+ sudo -u git -H sed 's/{{DB_ENCODING}}/utf8/' -i config/database.yml
+ sudo -u git -H sed 's/{{DB_HOST}}/db/' -i config/database.yml
+ sudo -u git -H sed 's/{{DB_PORT}}/tcp://172.17.0.43:3306/' -i config/database.yml
sed: -e expression #1, char 20: unknown option to `s'
```

**Comment by diresi** [comment]
Thats good. Your collision is $DB_PORT. You should also rename your "db" container.

**Comment by mikehaertl** [comment]
Yup, just found that out, too. Renamed it to `mysql` and it seems to work now.

Thanks!

**Comment by mikehaertl** [comment]
For completeness, here's a full `docker-compose.yml` that works. I think, this could be included in the README as it gets you up and running in no time at all:

```
gitlab:
    image: sameersbn/gitlab:7.10.1
    ports:
        - "8080:80"
    expose:
        - "80"
    links:
        - mydb
        - myredis
    environment:
        DB_TYPE: mysql
        DB_HOST: mydb
        DB_NAME: gitlab
        DB_USER: gitlab
        DB_PASS: gitlab
        REDIS_HOST: myredis
        REDIS_PORT: 6379
mydb:
    image: mysql:5.6.22
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gitlab
        MYSQL_USER: gitlab
        MYSQL_PASSWORD: gitlab
myredis:
    image: redis:3.0.0
    ports:
        - "6379:6379"
    expose:
        - "6379"
```
