### ISSUE TITLE
Issue with redis container

### ISSUE THREAD

**Issue by frdmn** [sameersbn/docker-gitlab#341]
I'm using the default `docker-compose` environment but my `sidekiq.log` throws the following errors:

    2015-06-10T11:33:09.830Z 547 TID-1uu1lc ERROR: heartbeat: Timed out connecting to Redis on 172.17.0.17:6379
    2015-06-10T11:33:10.216Z 547 TID-ciobk ERROR: Timed out connecting to Redis on 172.17.0.17:6379
    2015-06-10T11:33:10.216Z 547 TID-ciobk ERROR: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.1.0/lib/redis/client.rb:307:in `rescue in establish_connection'

Redis seem to run on the redis container, though:

```shell
root@chewbacca ~ # docker-enter dockergitlab_redis_1
root@9cf1ba022901:~ # ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
redis        1  0.0  0.0  36996  7460 ?        Ssl  09:47   0:02 /usr/bin/redis-server 0.0.0.0:6379
root        45  0.0  0.0  46624  1424 ?        S    11:34   0:00 su - root
root        46  0.0  0.0  18168  1860 ?        S    11:34   0:00 -su
root        57  0.0  0.0  15564  1112 ?        R+   11:34   0:00 ps aux
```

Here's my docker-compose.yml:

```yaml
postgresql:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:7.11.4
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Europe/Berlin
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Berlin
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=gitlab@git.frd.mn
    - GITLAB_EMAIL_REPLY_TO=noreply@git.frd.mn
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
```
Any ideas?
