### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by arno0203** [sameersbn/docker-gitlab#383]
Hi, 
I use this docker-compose file to start docker-gitlab image.
```
gitlab:
    image: sameersbn/gitlab
    ports:
        - "10080:80"
        - "10022:22"  
    links:
        - redisgitlab:redisio
        - mysqlgitlab:mysql  
    environment:
        - GITLAB_PORT=10080
        - GITLAB_SSH_PORT=10022  
        - GITLAB_HOST=localhost
        - GITLAB_UTL=http://localhost:8080
        - REDIS_HOST=redis
        - REDIS_PORT=6379   
    volumes:
        - /srv/docker/gitlab/gitlab:/home/git/data

redisgitlab:
    image: sameersbn/redis
    volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis

mysqlgitlab:
    image: sameersbn/mysql
    volumes:
        - /srv/docker/gitlab/mysql:/var/lib/mysql
    environment:
        - DB_NAME=gitlabhq_production
        - DB_USER=gitlab
        - DB_PASS=gitlab
```
After start there is this log in console 

```
Attaching to docker_mysqlgitlab_1, docker_redisgitlab_1, docker_gitlab_1
[36mmysqlgitlab_1 | [0mCreating database "gitlabhq_production"...
[36mmysqlgitlab_1 | [0mGranting access to database "gitlabhq_production" for user "gitlab"...
[36mmysqlgitlab_1 | [0m150716 12:52:45 mysqld_safe Logging to syslog.
[36mmysqlgitlab_1 | [0m150716 12:52:45 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
[33mredisgitlab_1 | [0m+ exec start-stop-daemon --start --chuid redis:redis --exec /usr/bin/redis-server -- /etc/redis/redis.conf
[33mredisgitlab_1 | [0m                _._                                                  
[33mredisgitlab_1 | [0m           _.-``__ ''-._                                             
[33mredisgitlab_1 | [0m      _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
[33mredisgitlab_1 | [0m  .-`` .-```.  ```\/    _.,_ ''-._                                   
[33mredisgitlab_1 | [0m (    '      ,       .-`  | `,    )     Running in stand alone mode
[33mredisgitlab_1 | [0m |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
[33mredisgitlab_1 | [0m |    `-._   `._    /     _.-'    |     PID: 1
[33mredisgitlab_1 | [0m  `-._    `-._  `-./  _.-'    _.-'                                   
[33mredisgitlab_1 | [0m |`-._`-._    `-.__.-'    _.-'_.-'|                                  
[33mredisgitlab_1 | [0m |    `-._`-._        _.-'_.-'    |           http://redis.io        
[33mredisgitlab_1 | [0m  `-._    `-._`-.__.-'_.-'    _.-'                                   
[33mredisgitlab_1 | [0m |`-._`-._    `-.__.-'    _.-'_.-'|                                  
[33mredisgitlab_1 | [0m |    `-._`-._        _.-'_.-'    |                                  
[33mredisgitlab_1 | [0m  `-._    `-._`-.__.-'_.-'    _.-'                                   
[33mredisgitlab_1 | [0m      `-._    `-.__.-'    _.-'                                       
[33mredisgitlab_1 | [0m          `-._        _.-'                                           
[33mredisgitlab_1 | [0m              `-.__.-'                                               
[33mredisgitlab_1 | [0m
[33mredisgitlab_1 | [0m[1] 16 Jul 12:52:44.446 # Server started, Redis version 2.8.4
[33mredisgitlab_1 | [0m[1] 16 Jul 12:52:44.446 * DB loaded from disk: 0.000 seconds
[33mredisgitlab_1 | [0m[1] 16 Jul 12:52:44.446 * The server is now ready to accept connections on port 6379
[33mredisgitlab_1 | [0m[1] 16 Jul 12:52:44.446 * The server is now ready to accept connections at /var/run/redis/redis.sock
[32mgitlab_1      | [0mWaiting for database server to accept connections
[32mgitlab_1      | [0mStarting supervisord...
[32mgitlab_1      | [0m2015-07-16 12:52:49,607 CRIT Supervisor running as root (no user in config file)
[32mgitlab_1      | [0m2015-07-16 12:52:49,607 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
[32mgitlab_1      | [0m2015-07-16 12:52:49,607 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
[32mgitlab_1      | [0m2015-07-16 12:52:49,607 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
[32mgitlab_1      | [0m2015-07-16 12:52:49,607 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
[32mgitlab_1      | [0m2015-07-16 12:52:49,607 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
[32mgitlab_1      | [0m2015-07-16 12:52:49,628 INFO RPC interface 'supervisor' initialized
[32mgitlab_1      | [0m2015-07-16 12:52:49,628 CRIT Server 'unix_http_server' running without any HTTP authentication checking
[32mgitlab_1      | [0m2015-07-16 12:52:49,628 INFO supervisord started with pid 1
[32mgitlab_1      | [0m2015-07-16 12:52:50,631 INFO spawned: 'sidekiq' with pid 261
[32mgitlab_1      | [0m2015-07-16 12:52:50,633 INFO spawned: 'unicorn' with pid 262
[32mgitlab_1      | [0m2015-07-16 12:52:50,635 INFO spawned: 'cron' with pid 263
[32mgitlab_1      | [0m2015-07-16 12:52:50,637 INFO spawned: 'nginx' with pid 264
[32mgitlab_1      | [0m2015-07-16 12:52:50,639 INFO spawned: 'sshd' with pid 265
[32mgitlab_1      | [0m2015-07-16 12:52:52,361 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:52:52,362 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:52:52,362 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:52:52,362 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:52:52,362 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:53:22,954 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:53:23,957 INFO spawned: 'sidekiq' with pid 331
[32mgitlab_1      | [0m2015-07-16 12:53:24,959 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:53:57,325 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:53:58,328 INFO spawned: 'sidekiq' with pid 382
[32mgitlab_1      | [0m2015-07-16 12:53:59,329 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:54:29,392 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:54:30,394 INFO spawned: 'sidekiq' with pid 433
[32mgitlab_1      | [0m2015-07-16 12:54:31,396 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:55:03,797 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:55:04,800 INFO spawned: 'sidekiq' with pid 484
[32mgitlab_1      | [0m2015-07-16 12:55:05,801 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:55:37,010 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:55:38,012 INFO spawned: 'sidekiq' with pid 535
[32mgitlab_1      | [0m2015-07-16 12:55:39,013 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:56:09,942 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:56:10,945 INFO spawned: 'sidekiq' with pid 586
[32mgitlab_1      | [0m2015-07-16 12:56:11,946 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:56:41,700 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:56:42,702 INFO spawned: 'sidekiq' with pid 637
[32mgitlab_1      | [0m2015-07-16 12:56:43,703 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:57:12,908 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:57:13,911 INFO spawned: 'sidekiq' with pid 688
[32mgitlab_1      | [0m2015-07-16 12:57:14,912 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:57:45,351 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:57:46,354 INFO spawned: 'sidekiq' with pid 739
[32mgitlab_1      | [0m2015-07-16 12:57:47,355 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[32mgitlab_1      | [0m2015-07-16 12:58:16,379 INFO exited: sidekiq (exit status 1; not expected)
[32mgitlab_1      | [0m2015-07-16 12:58:17,382 INFO spawned: 'sidekiq' with pid 790
[32mgitlab_1      | [0m2015-07-16 12:58:18,383 INFO success: sidekiq entered RUNNING state, process has st
```

I think it's ok but when i try to go on http://localhost:10080 I see an error 500.
Could you help me ?

Thank
(Sorry for my english)

**Comment by sameersbn** [comment]
@arno0203 The log indicates that sidekiq is not starting. Please make sure that the docker host has 1 GB or more of available RAM. This is one common reason that this happens

**Comment by arno0203** [comment]
@sameersbn Thanks for your comment.
I execute sudo docker info 
```
Containers: 3
Images: 39
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 7.686 GiB
Name: ADO-POR-2
ID: DIEV:JOXE:O236:ZKCW:6S7Q:LJS5:YUKK:6NJG:3IJV:GWUU:OUQD:MTBD
WARNING: No swap limit support
```

After that I try to set the memory limit in docker_compose.yml file for the gitlab image

```
gitlab:
    image: sameersbn/gitlab
    mem_limit: 2000m     
    ports:
        - "10080:80"
        - "10022:22"  
    links:
        - redisgitlab:redisio
        - mysqlgitlab:mysql  
    environment:
        - GITLAB_PORT=10080
        - GITLAB_SSH_PORT=10022  
        - GITLAB_HOST=localhost
        - GITLAB_UTL=http://localhost:8080
        - REDIS_HOST=redis
        - REDIS_PORT=6379   
    volumes:
        - /srv/docker/gitlab/gitlab:/home/git/data

redisgitlab:
    image: sameersbn/redis
    volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis

mysqlgitlab:
    image: sameersbn/mysql
    volumes:
        - /srv/docker/gitlab/mysql:/var/lib/mysql
    environment:
        - DB_NAME=gitlabhq_production
        - DB_USER=gitlab
        - DB_PASS=gitlab
```

And the result is that 

```
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
docker_gitlab_1     1.96%               439 MB/2.097 GB     20.93%              2.923 MB/1.212 MB
```

But there is not change 
```
gitlab_1      | 2015-07-17 08:45:52,586 INFO exited: sidekiq (exit status 1; not expected)
```

Thank
