### ISSUE TITLE
Problem when use variable GITLAB_ROOT_PASSWORD

### ISSUE THREAD

**Issue by fernandoneto** [sameersbn/docker-gitlab#416]
hi

im playing with gitlab and im facing a little issue when i use the variable `GITLAB_ROOT_PASSWORD`.
if i do not set this variable and use the default values the login process work without problem, but if i set this variable  after launching the container im not able to login with user root and the password i choose. if i use the default password the problem persist. 
![gitlab_login](https://cloud.githubusercontent.com/assets/6515784/9853873/d4a6a126-5afd-11e5-8b3f-a5dd7b112f1e.png)

im using CoreOS beta. 
best regards 
Fernando Neto

**Comment by sameersbn** [comment]
@fernandoneto are you sure? I had no problem starting gitlab using the following docker compose file and logging in as `root` with the password specified in `GITLAB_ROOT_PASSWORD`.

```yaml
postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
gitlab:
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Asia/Kolkata
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=git.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=admin@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
    - GITLAB_ROOT_PASSWORD=password
redis:
  image: sameersbn/redis:latest
```

Please note that `GITLAB_ROOT_PASSWORD` only takes effect on the first run of the container. Once the database has been initialized you cannot specify `GITLAB_ROOT_PASSWORD` to change the root users password.
