### ISSUE TITLE
docker-compose & gitlab 7.0.0 : unable to start

### ISSUE THREAD

**Issue by n1b0r** [sameersbn/docker-gitlab#419]
Hello,

I would like to migrate a gitlab v7.0.0 from a physical host to a dockerized latest version.

I'm unable to start the gitlab container with the docker-compose.yml file provided (with 7.0.0 version):
```
gitlab:
  image: sameersbn/gitlab:7.0.0
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Asia/Kolkata
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=admin@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
``` 

Here is the docker-compose output :
```
robin@fixe:~/sources/_docker/gitlab$ sudo rm -rf /srv/docker/gitlab/ && docker-compose rm -f && docker-compose up
[sudo] password for robin: 
Going to remove gitlab_gitlab_1, gitlab_redis_1, gitlab_postgresql_1
Removing gitlab_postgresql_1...
Removing gitlab_redis_1...
Removing gitlab_gitlab_1...
Creating gitlab_postgresql_1...
Creating gitlab_redis_1...
Creating gitlab_gitlab_1...
Attaching to gitlab_postgresql_1, gitlab_redis_1, gitlab_gitlab_1
postgresql_1 | Initializing database...
gitlab_1     | User: root Password: eegea5Weew3n
redis_1      | Starting redis-server...
redis_1      |                 _._                                                  
redis_1      |            _.-``__ ''-._                                             
redis_1      |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1      |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |                                  
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |       `-._    `-.__.-'    _.-'                                       
redis_1      |           `-._        _.-'                                           
redis_1      |               `-.__.-'                                               
redis_1      | 
redis_1      | [1] 15 Sep 19:13:28.547 # Server started, Redis version 2.8.4
redis_1      | [1] 15 Sep 19:13:28.547 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | [1] 15 Sep 19:13:28.547 * The server is now ready to accept connections on port 6379
redis_1      | [1] 15 Sep 19:13:28.547 * The server is now ready to accept connections at /var/run/redis/redis.sock
gitlab_1     | Creating SSH2 RSA key; this may take some time ...
gitlab_1     | Creating SSH2 DSA key; this may take some time ...
gitlab_1     | Creating SSH2 ECDSA key; this may take some time ...
gitlab_1     | Creating SSH2 ED25519 key; this may take some time ...
gitlab_1     | invoke-rc.d: policy-rc.d denied execution of restart.
gitlab_1     | Starting openssh server...
gitlab_1     | Starting nginx...
postgresql_1 | Creating user "gitlab"...
postgresql_1 | Creating database "gitlabhq_production"...
postgresql_1 | Granting access to database "gitlabhq_production" for user "gitlab"...
postgresql_1 | Starting PostgreSQL server...
postgresql_1 | 2015-09-15 19:13:32 UTC [73-1] LOG:  database system was shut down at 2015-09-15 19:13:31 UTC
postgresql_1 | 2015-09-15 19:13:32 UTC [73-2] LOG:  MultiXact member wraparound protections are now enabled
postgresql_1 | 2015-09-15 19:13:32 UTC [1-1] LOG:  database system is ready to accept connections
postgresql_1 | 2015-09-15 19:13:32 UTC [77-1] LOG:  autovacuum launcher started
gitlab_1     | Migrating database...
gitlab_gitlab_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping gitlab_redis_1...
Stopping gitlab_postgresql_1...
Exception in thread Thread-1 (most likely raised during interpreter shutdown):robin@fixe:~/sources/_docker/gitlab$ 
``` 

How to have a running 7.0.0 gitlab container ?

**Comment by sameersbn** [comment]
@n1b0r looks like the database migration step may be failing. Can you retry after adding `DEBUG_ENTRYPOINT=true` in gitlab environment. It will display the commands being executed and should reveal the command at which the error occurs.

**Comment by sameersbn** [comment]
p.s. you might find information in #367 useful.

**Comment by n1b0r** [comment]
Hello, thanks for your reply.

Unfortunately, adding the env var DEBUG_ENTRYPOINT=true did not display anything in logs.

Here is the current docker-compose.yml :
```
postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:7.0.0
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG_ENTRYPOINT=true
    - TZ=Asia/Kolkata
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=admin@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
``` 

Here is the docker compose log :
```
robin@fixe:~/sources/_docker/gitlab$ sudo rm -rf /srv/docker/gitlab/ && docker-compose rm -f && docker-compose up
Going to remove gitlab_gitlab_1, gitlab_redis_1, gitlab_postgresql_1
Removing gitlab_postgresql_1...
Removing gitlab_redis_1...
Removing gitlab_gitlab_1...
Creating gitlab_postgresql_1...
Creating gitlab_redis_1...
Creating gitlab_gitlab_1...
Attaching to gitlab_postgresql_1, gitlab_redis_1, gitlab_gitlab_1
postgresql_1 | Initializing database...
redis_1      | Starting redis-server...
redis_1      |                 _._                                                  
redis_1      |            _.-``__ ''-._                                             
redis_1      |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1      |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |                                  
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |       `-._    `-.__.-'    _.-'                                       
redis_1      |           `-._        _.-'                                           
redis_1      |               `-.__.-'                                               
redis_1      | 
redis_1      | [1] 16 Sep 10:28:39.620 # Server started, Redis version 2.8.4
redis_1      | [1] 16 Sep 10:28:39.620 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | [1] 16 Sep 10:28:39.620 * The server is now ready to accept connections on port 6379
redis_1      | [1] 16 Sep 10:28:39.620 * The server is now ready to accept connections at /var/run/redis/redis.sock
gitlab_1     | User: root Password: ooGe4ku9raek
gitlab_1     | Creating SSH2 RSA key; this may take some time ...
gitlab_1     | Creating SSH2 DSA key; this may take some time ...
gitlab_1     | Creating SSH2 ECDSA key; this may take some time ...
gitlab_1     | Creating SSH2 ED25519 key; this may take some time ...
gitlab_1     | invoke-rc.d: policy-rc.d denied execution of restart.
gitlab_1     | Starting openssh server...
gitlab_1     | Starting nginx...
postgresql_1 | Creating user "gitlab"...
postgresql_1 | Creating database "gitlabhq_production"...
postgresql_1 | Granting access to database "gitlabhq_production" for user "gitlab"...
postgresql_1 | Starting PostgreSQL server...
postgresql_1 | 2015-09-16 10:28:42 UTC [73-1] LOG:  database system was shut down at 2015-09-16 10:28:42 UTC
postgresql_1 | 2015-09-16 10:28:42 UTC [73-2] LOG:  MultiXact member wraparound protections are now enabled
postgresql_1 | 2015-09-16 10:28:42 UTC [77-1] LOG:  autovacuum launcher started
postgresql_1 | 2015-09-16 10:28:42 UTC [1-1] LOG:  database system is ready to accept connections
gitlab_1     | Migrating database...
gitlab_gitlab_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping gitlab_redis_1...
Stopping gitlab_postgresql_1...
robin@fixe:~/sources/_docker/gitlab$ 
```

As you can see, I remove the host directory containing volume before starting compose, so there are no backups on volumes.

Where did I do wrong ?

**Comment by sameersbn** [comment]
I think the `DEBUG_ENTRYPOINT` option was added after the `7.0.0` release.

You mentioned you are trying to migrate from a physical installation. But you have not tried any of the migration yet right. You are trying to get instructions in the quickstart guide working right? If yes, then 
- paste your `docker-compose.yml` file and the logs. The logs you pasted do not match the docker-compose.yml specification.
- Make sure that your docker host has atleast 1 GB of available RAM before launching gitlab
- Try deleting the contents of `/srv/docker/gitlab` and start over using the quickstart instructions.

Do not try to perform any migration bits now. The migration can be done by restoring a backup once you have gitlab running.

**Comment by sameersbn** [comment]
In the mean time I am checking using your docker-compose.yml file.
Will let you know how it goes.

**Comment by sameersbn** [comment]
@n1b0r I spent some time to check the issue.

The `7.0.0` version you are trying to use does not have all the features that the most recent releases have. You should refer to the readme of that version instead of the master https://github.com/sameersbn/docker-gitlab/blob/v7.0.0/README.md.

However I found out the problem. You have to add the `DB_USER`, `DB_PASS` and `DB_NAME` variables to the gitlab containers environment as well. The `7.0.0` image does not fetch this information from the docker link.

The below docker compose file should work.

```yaml
postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Asia/Kolkata
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=app.damagehead.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=admin@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
```
