### ISSUE TITLE
Webhooks don't trigger

### ISSUE THREAD

**Issue by rkcreation** [sameersbn/docker-gitlab#447]
Hi,

If someone could help me, I certainly miss some conf...

I have a Gitlab container running (thanks !), all features working, but there is only one weird thing with webhook : 
- when I hit Test webhook, it works
- when I push from my local repo to the gitlab remote repo, webhooks don't trigger anything

I use git bash for windows (maybe ?), and I've tested with requestb.in and my own script.
Gitlab container is started with docker-compose, and Web UI is behind an apache2 proxy.
I can't figure what I'm doing wrong.

Is there any specific configuration or workflow ?

Thanks in advance ! And thanks yet for the work !

PS : my docker-compose.yml (some private vars are replaced of course)
````
data:
  image: busybox
  volumes:
    - ---:/var/lib/postgresql
    - ---:/var/lib/redis
    - ---:/home/git/data
    - ---:/home/git/gitlab-shell/hooks
dbpg:
  image: sameersbn/postgresql:latest
  environment:
    - DB_NAME=gitlabhq_production
    - DB_USER=gitlab
    - DB_PASS=---
  volumes_from:
    - data
redis:
  image: sameersbn/redis:latest
  volumes_from:
    - data
gitlab:
  image: sameersbn/gitlab:8.0.2
  environment:
    - TZ=Europe/Paris
    - GITLAB_HOST=---
    - GITLAB_EMAIL=---
    - GITLAB_EMAIL_REPLY_TO=---
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_EXPIRY=1209600
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_TIMEZONE=Paris
    - GITLAB_SECRETS_DB_KEY_BASE=---
    - SMTP_ENABLED=true
    - SMTP_STARTTLS=true
    - SMTP_TLS=true
    - SMTP_AUTHENTICATION=login
    - SMTP_OPENSSL_VERIFY_MODE=none
         -- all smpt confs (SMTP_PORT....)
  links:
    - dbpg:postgresql
    - redis:redisio
  volumes_from:
    - data
  ports:
    - "10080:80"
    - "10022:22"
````
