### ISSUE TITLE
How to enabled new relic?

### ISSUE THREAD

**Issue by junxy** [sameersbn/docker-gitlab#473]
Hi

Need add some new relic environment variable support?

/home/git/gitlab/config/newrelic.yml
```
# New Relic configuration file
#
# This file is here to make sure the New Relic gem stays
# quiet by default.
#
# To enable and configure New Relic, please use
# environment variables, e.g. NEW_RELIC_ENABLED=true

production:
  enabled: false

development:
  enabled: false

test:
  enabled: false
```
