### ISSUE TITLE
Relative url not respected by dynamic assets loading

### ISSUE THREAD

**Issue by JStumpp** [sameersbn/docker-gitlab#481]
The parameter GITLAB_RELATIVE_URL_ROOT is not respected by the dynamic assets loading of application-****.js

Tested with Version: sameersbn/gitlab:8.1.0 and sameersbn/gitlab:8.1.0-1

In the following example the GITLAB_RELATIVE_URL_ROOT is set to /git
![image](https://cloud.githubusercontent.com/assets/4624747/10713709/7f67ac5e-7ac5-11e5-92fc-62686e2745dd.png)

**Comment by sameersbn** [comment]
seems that assets need to be precompiled when relative url is used. will try to figure out a fix.

**Comment by sameersbn** [comment]
`8.1.0-2` fixes this issue by recompiling the assets when `GITLAB_RELATIVE_URL_ROOT` is used. This means that the container will take a little longer to start for the first time or after an upgrade. When you update, please delete the `tmp` directory from the data volume before starting the container. This automatically happens on new GitLab releases not on point releases.

**Comment by JStumpp** [comment]
Absolutely wonderful! Thanks a lot!

**Comment by jbaxley** [comment]
This is still a problem.  using Gitlab 8.3.2

**Comment by sameersbn** [comment]
@jbaxley are you sure? can you share the details of the behaviour your seeing?

**Comment by jbaxley** [comment]
When I log into my gitlab I see that the icons are just blocks and when looking at the webdev tools that the server is trying to load files from server/assests and not from server/gitlab/assests.  It doesn't appear that the workhorse is recompiling the assests for use with the new relative_url_root path.

**Comment by sameersbn** [comment]
Can you share your `docker-compose.yml` so that I can reproduce the issue?

I have tested successfully using:

```yaml
postgresql:
   restart: always
   image: sameersbn/postgresql:9.4-11
   environment:
     - DB_USER=gitlab
     - DB_PASS=password
     - DB_NAME=gitlabhq_production
   volumes:
     - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
   restart: always
   image: sameersbn/gitlab:8.3.2
   links:
     - redis:redisio
     - postgresql:postgresql
   ports:
     - "10080:80"
     - "10022:22"
   environment:
     - DEBUG=false

     - TZ=Asia/Kolkata
     - GITLAB_TIMEZONE=Kolkata

     - 
GITLAB_SECRETS_DB_KEY_BASE=r73WWLcc4z3pkRqhp3w4HcXjLdtgcm7JJFvWF3K74tFrKfRFR7fXC9Pf3bfw4H3K

     - GITLAB_HOST=git.example.com
     - GITLAB_PORT=80
     - GITLAB_SSH_PORT=10022
     - GITLAB_RELATIVE_URL_ROOT=/gitlab

   volumes:
     - /srv/docker/gitlab/gitlab:/home/git/data
redis:
   restart: always
   image: sameersbn/redis:latest
   command:
     - --loglevel warning
   volumes:
     - /srv/docker/gitlab/redis:/var/lib/redis
```

On Monday 11 January 2016 11:00 PM, jbaxley wrote:
> When I log into my gitlab I see that the icons are just blocks and when
> looking at the webdev tools that the server is trying to load files from
> server/assests and not from server/gitlab/assests. It doesn't appear
> that the workhorse is recompiling the assests for use with the new
> relative_url_root path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-gitlab/issues/481#issuecomment-170626550>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com
