### ISSUE TITLE
issues with missing icons (assets) via using GITLAB_RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by BeneDicere** [sameersbn/docker-gitlab#521]
Hi,
version 8.2 worked well but since version 8.2.1 icons in side-bar and header are not showing up ![sidebar](https://cloud.githubusercontent.com/assets/5327850/11495698/93812926-980d-11e5-8727-b11ac3bb7ad5.png).
The JavaScript console shows that it is ignoring the relative url and looking for something in ROOT/assets/... I don't know whether this is a GitLab, Docker Image or Apache issue, but because it worked well until now i hope its a Docker Image issue. :)

Thanks for the Image, until now it worked very well and made the deployment very easy.

**Comment by sameersbn** [comment]
I do not see this issue. For the test I used the sample `docker-compose.yml` file with `GITLAB_RELATIVE_URL_ROOT=/gitlab`

**Comment by sameersbn** [comment]
Are you using apache as a load balancer?

**Comment by BeneDicere** [comment]
we are using apache as reverse proxy, thats all we have configured:

  ProxyRequests Off
  ProxyPass /gitlab http://localhost:10080/gitlab
  <Location /gitlab>
    ProxyPassReverse http://localhost:10080/gitlab
  </Location>

Strange, because beside of the gitlab image (it was updated) nothing changed. I will see whether i can find another reason for this behaviour.
Thanks for your fast answer.

**Comment by sameersbn** [comment]
can you try connecting directly to `http://localhost:10080/gitlab` to verify in the urls are correct?
p.s. i think `ProxyPassReverse http://localhost:10080/gitlab` should be `ProxyPassReverse http://localhost:10080`. not a 100% sure.

**Comment by BeneDicere** [comment]
bypassing the proxy works. i will see what else the reason for this issue is, strange that this did not happen before. thanks for the pointer, sorry for the noise.

**Comment by sameersbn** [comment]
In case you have not tried already, please clear the browser cache and retry.

**Comment by BeneDicere** [comment]
This was done with different browsers and of course a cache clear. ;) Beside of bypassing the proxy the current workaround is to add a separate proxy rule for the "/asset" path to "/gitlab/asset". But i think this is  a local and no general issue.
Once again, thanks for this great image and your fast help.

**Comment by mlewe** [comment]
I have the same problem. In the generated CSS files the wrong asset path is referenced. E.g.:
``@font-face{font-family:'FontAwesome';src:url("/assets/fontawesome-webfont-....eot?v=4.4.0"); ``
But GITLAB_RELATIVE_URL_ROOT is set to "/git".

**Comment by pylight** [comment]
Thanks for fixing it for version 8.2.3, it's working there nicely with relative url & reverse proxy. But in latest version 8.3.0 I'm facing the same problem again. Is this a known bug of this version?

**Comment by sameersbn** [comment]
@pylight can you please share your `docker-compose.yml` or `docker run` command. I testing using the sample `docker-compose.yml` with `GITLAB_RELATIVE_URL_ROOT=/gitlab` and everything seems to be working fine.

**Comment by pylight** [comment]
Sure:
```
    postgres:
      image: localhost:5000/postgres
      environment:
        - POSTGRES_USER=gitlab
        - POSTGRES_PASSWORD=<somePW>
      ports:
        - "127.0.0.1:5432:5432"
    redis:
      image: localhost:5000/redis
      ports:
        - "127.0.0.1:6379:6379"
    service:
      image: sameersbn/gitlab:8.2.3
      links:
        - redis:redisio
        - postgres:postgresql
      ports:
        - "127.0.0.1:11080:80"
        - "11022:22"
      environment:
        - TZ=Europe/Berlin
        - SMTP_ENABLED=true
        - SMTP_DOMAIN=www.ourDomain.net
        - SMTP_HOST=www.ourDomain.net
        - SMTP_PORT=25
        - GITLAB_TIMEZONE=Berlin
        - GITLAB_HOST=ourDomain.net
        - GITLAB_HTTPS=true
        - GITLAB_PORT=443
        - GITLAB_SSH_PORT=11022
        - GITLAB_SSH_HOST=subdomain.ourDomain.net
        - GITLAB_RELATIVE_URL_ROOT=/gitlab
        - GITLAB_EMAIL=noreply@ourDomain.net
        - GITLAB_EMAIL_REPLY_TO=noreply@ourDomain.net
        - GITLAB_EMAIL_DISPLAY_NAME=Shared Gitlab
        - GITLAB_BACKUPS=daily
        - GITLAB_BACKUP_TIME=01:00
        - GITLAB_GRAVATAR_ENABLED=false
        - GITLAB_SECRETS_DB_KEY_BASE=<someKey>
        - DB_TYPE=postgres
        - DB_NAME=gitlab
        - DB_USER=gitlab
        - DB_PASS=<somePW>
        - http_proxy=<corporateProxy>
        - https_proxy=<corporateProxy>
        - no_proxy="<list of some internal servers>"
      volumes:
        - /var/run/docker.sock:/run/docker.sock
        - /usr/bin/docker:/bin/docker
        - /data/gitlab/:/home/git/data/
        - /data/gitlab/gitlab/:/var/log/gitlab
```
Note: I've upgraded from gitlab 7.10.4 (and just replaces the "image" setting of "service" + added a GITLAB_SECRETS_DB_KEY_BASE)
