### ISSUE TITLE
endless redirect

### ISSUE THREAD

**Issue by freeseacher** [sameersbn/docker-gitlab#543]
Hi! 
i found a problem with endless redirect on latest version fe693c7586a7
while trying to access to https://site-name/project_group/project_name.git i got endless redirect with 302 code

[wget.txt](https://github.com/sameersbn/docker-gitlab/files/67412/wget.txt)

server side logs are
==> log/production.log <==
Started GET "/project_group/project_name.git/" for 127.0.0.1 at 2015-12-19 13:00:56 +0500
Processing by ProjectsController#show as */*
  Parameters: {"namespace_id"=>"project_group", "id"=>"project_name.git"}
Redirected to https://gitlab.ertelecom.ru/project_group/project_name.git/
Filter chain halted as :project rendered or redirected
Completed 302 Found in 84ms (ActiveRecord: 2.9ms)

my configurations is
```
gitlab:
  restart: always
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "80:80"
    - "10022:22"
    - "443:443"
  environment:
    - TZ=Asia/Yekaterinburg
    - GITLAB_SECRETS_DB_KEY_BASE=XXXXXX
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=XXXXX
    - SMTP_HOST=XXXXX
    - SMTP_PORT=25
    - SMTP_USER=XXXXX
    - SMTP_PASS=XXXXX
    - GITLAB_TIMEZONE=Ekaterinburg
    - GITLAB_HOST=XXXXX
    - GITLAB_HTTPS=true
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=XXXXX
    - GITLAB_EMAIL_REPLY_TO=XXXXX
    - GITLAB_PROJECTS_MERGE_REQUESTS=true
    - NGINX_WORKERS=2
    - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab.crt
    - SSL_KEY_PATH=/home/git/data/certs/gitlab.key
    - SSL_SELF_SIGNED=true
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
    - LDAP_ENABLED=true
    - LDAP_HOST=XXXXX
    - LDAP_PORT=3268
    - LDAP_BIND_DN=XXXXX
    - LDAP_PASS=XXXXX
    - LDAP_BASE=DC=XXXXX
    - IMAP_ENABLED=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
```

i've got that trouble while trying to debug another issue with https auth it always fail

**Comment by sameersbn** [comment]
@freeseacher sorry for the late response. I tested using the following spec without any issues:

```yaml
postgresql:
  restart: always
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql

redis:
  restart: always
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis

gitlab:
  restart: always
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "80:80"
    - "10022:22"
    - "443:443"
  environment:
    - TZ=Asia/Yekaterinburg
    - GITLAB_SECRETS_DB_KEY_BASE=XXXXXX
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=
    - SMTP_HOST=
    - SMTP_PORT=
    - SMTP_USER=
    - SMTP_PASS=
    - GITLAB_TIMEZONE=Ekaterinburg
    - GITLAB_HOST=git.example.com
    - GITLAB_HTTPS=true
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_PROJECTS_MERGE_REQUESTS=true
    - NGINX_WORKERS=2
    - SSL_CERTIFICATE_PATH=/home/git/data/certs/gitlab.crt
    - SSL_KEY_PATH=/home/git/data/certs/gitlab.key
    - SSL_SELF_SIGNED=true
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
    - LDAP_ENABLED=false
    - LDAP_HOST=
    - LDAP_PORT=
    - LDAP_BIND_DN=
    - LDAP_PASS=
    - LDAP_BASE=
    - IMAP_ENABLED=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
```

Can you try with the most recent release to see it it helps?
