### ISSUE TITLE
"no implicit conversion of Fixnum into String" with external mysql database

### ISSUE THREAD

**Issue by ShaggyYeti** [sameersbn/docker-gitlab#57]
Hello.
I found bug. I create container with command:

``` bash
docker run -name gitlab -i -t --rm -link mysql:mysql -v /opt/docker/gitlab/data:/home/git/data -e "DB_USER=gitlab" -e "DB_PASS=1" -e "DB_NAME=gitlabhq_production" sameersbn/gitlab:latest app:rake gitlab:setup
```

And I get the error: "gitlab no implicit conversion of Fixnum into String".
The error appears because value of key "password" doesn't wrote in quotes (in file gitlab/config/database.yml):

``` yml
production:
  adapter: mysql2
  database: gitlab_production
  host: 172.27.0.5
  port: 3306
  username: gitlab
  password: 1
  encoding: utf8
```

The solution to this problem is using additional quotes in bash command (look at DB_PASS):

``` bash
docker run -name gitlab -i -t --rm -link mysql:mysql -v /opt/docker/gitlab/data:/home/git/data -e "DB_USER=gitlab" -e "DB_PASS=\"1\"" -e "DB_NAME=gitlabhq_production" sameersbn/gitlab:latest app:rake gitlab:setup
```
