### ISSUE TITLE
First time startup - cannot login

### ISSUE THREAD

**Issue by xueshanf** [sameersbn/docker-gitlab#657]
I am trying kubernetes configuration to start docker. My pods and services seems running fine, but when I try to login the first time, all I have is "Change your  Password"  window, asking for new password and confirm new password, but no username field. Trying to login will give errors.

What is missing?

Thanks!

<img width="460" alt="screen shot 2016-04-06 at 5 19 28 pm" src="https://cloud.githubusercontent.com/assets/4178225/14336730/cc125144-fc1b-11e5-8878-c5ae1f5f4b5b.png">

**Comment by sameersbn** [comment]
since GitLab 8.6 there is no default `root` user password. Once you create a password you need to login as the `root` user.

**Comment by xueshanf** [comment]
On Thu, Apr 7, 2016 at 1:20 AM, Sameer Naik <notifications@github.com>
wrote:

> since GitLab 8.6 there is no default root user password. Once you create
> a password you need to login as the root user.
>

The problem is that I cannot pass password change:

Change your password
7 errors prohibited this user from being saved:

   - Email can't be blank
   - Password can't be blank
   - Name can't be blank
   - Notification email can't be blank
   - Notification email is invalid
   - Username can contain only letters, digits, '_', '-' and '.'. Cannot
   start with '-' or end in '.'.
   - Username can't be blank


Xueshan

**Comment by sameersbn** [comment]
Are you seeing the same issue with docker-compose?

**Comment by sameersbn** [comment]
I see the issue on kubernetes. Wonder what the cause could be. Will try to figure it out. Until then you can try adding `GITLAB_ROOT_PASSWORD` to the the containers env to bypass that screen.

**Comment by xueshanf** [comment]
On Fri, Apr 8, 2016 at 9:04 AM, Sameer Naik <notifications@github.com>
wrote:

> I see the issue on kubernetes. Wonder what the cause could be. Will try to
> figure it out. Until then you can try adding GITLAB_ROOT_PASSWORD to the
> the containers env to bypass that screen.
>

Yup!  Use GITLAB_ROOT_PASSWORD env does allow root to login!

You can close this ticket.

Xueshan

**Comment by sameersbn** [comment]
If the gitlab pod is deleted and recreated again it seems to work. Looks to be an upstream issue.

**Comment by JesperWe** [comment]
I am seeing exactly the same problem after a fresh install using apt-get on Ubuntu 14.04.
Restart gitlab does not help.

**Comment by madmas** [comment]
I just did a fresh install on a raspberrypi with raspbian. When I try to change the password initially, I get the screen shown at top.

**Comment by JesperWe** [comment]
This should probably be reopened as an issue at gitlab.com if you have the time. AFAIK Gitlab (the company) is not using github (the site) to track issues for gitlab (the product) anymore.

**Comment by sameersbn** [comment]
I am seeing the issue on docker 4 mac beta too. However I found that the issue is seen in Firefox, but not in Chrome. Can you confirm of you see the same?

**Comment by madmas** [comment]
Yes, I can confirm that, changing the password and logging in with Chrome instead of Firefox works fine.

**Comment by adventurist** [comment]
Experiencing this with a fresh install in Ubuntu 16.04. Browsing to gitlab via Chrome 54

**Comment by radut** [comment]
If someone else gets into this, first check if you have any health check that pings port of gitlab. It seems that if there is another request made to gitlab interface at first screen "enter password" it will recreate another token for allowing you to set root password, disabling current one that you achieved in browser.

Conclusion:
make sure no other GET / request is made to gitlab while the first screen is displayed

**Comment by eXpies** [comment]
> If someone else gets into this, first check if you have any health check that pings port of gitlab. It seems that if there is another request made to gitlab interface at first screen "enter password" it will recreate another token for allowing you to set root password, disabling current one that you achieved in browser.
Conclusion:
make sure no other GET / request is made to gitlab while the first screen is displayed

Confirmed!
Temporary removing Health Check, resolves the problem.
Thanks  @radut !

Although, the warning stated 11 errors:
```
Email can't be blank
Password can't be blank
Namespace route can't be blank
Namespace name can't be blank
Namespace name can contain only letters, digits, '_', '.', dash and space.
Name can't be blank
Notification email can't be blank
Notification email is invalid
Username can't be blank
Username can't be blank
Username can contain only letters, digits, '_', '-' and '.'. Cannot start with '-' or end in '.', '.git' or '.atom'.
```
Here is my docker-compose.yml:
```
  gitlab:
    image: gitlab/gitlab-ce:10.8.4-ce.0
    restart: on-failure
    networks:
      static:
        ipv4_address: 10.11.12.17
#    healthcheck:
#      test: "curl -sL http://localhost:80 -o /dev/null || exit 1"
#      interval: 30s
#      timeout: 10s
#      retries: 5
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://<HOST>:443'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/certs/cert.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/certs/cert.key"
        gitlab_rails['gitlab_https'] = true
        gitlab_rails['gitlab_port'] = 443
    ports:
      - 443:443
    volumes:
      - /docker_data/gitlab/config:/etc/gitlab:Z
      - /docker_data/gitlab/logs:/var/log/gitlab:Z
      - /docker_data/gitlab/data:/var/opt/gitlab:Z
```
