### ISSUE TITLE
Networking problems with 8.7.6 image

### ISSUE THREAD

**Issue by qwc** [sameersbn/docker-gitlab#668]
Hi,

I've got problems getting the 8.6.6 image to run.
````
gitlab_1           | Initializing logdir...
gitlab_1           | Initializing datadir...
gitlab_1           | Installing configuration templates...
gitlab_1           | SSL keys and certificates were not found.
gitlab_1           | Assuming that the container is running behind a HTTPS enabled load balancer.
gitlab_1           | Configuring gitlab...
gitlab_1           | Configuring gitlab::database
gitlab_1           | ERROR: 
gitlab_1           |   Please configure the database connection.
gitlab_1           |   Refer http://git.io/wkYhyA for more information.
gitlab_1           |   Cannot continue without a database. Aborting...
gitlab_1           | 
gitlab866_gitlab_1 exited with code 0
````

gitlab 8.6.5-1 is running after i've updated my docker-compose.yml with ````- DB_ADAPTER=postgresql````

Here's the complete config:
````
postgresqlgitlab:
  image: sameersbn/postgresql:9.4-19
  environment:
    - DB_USER=<user>
    - DB_PASS=<password>
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
  volumes:
    - /srv/data/docker/gitlab/postgres/data:/var/lib/postgresql
  restart: always
gitlab:
  image: sameersbn/gitlab:8.6.5-1
  ports:
    - "10080:80"
    - "42420:22"
  links:
    - redisgitlab:redisio
    - postgresqlgitlab:postgresql
  working_dir: /home/git/gitlab
  environment:
    - GITLAB_SECRETS_DB_KEY_BASE=<secret>
    - GITLAB_HOST=gitlab.<domain>
    - GITLAB_PORT=443
    - GITLAB_HTTPS=true
    - GITLAB_EMAIL=gitlab@<domain>
    - DB_ADAPTER=postgresql
    - DB_NAME=gitlabhq_production
    - DB_TYPE=postgres
    - DB_USER=<user>
    - DB_PASS=<password>
    - GITLAB_SSH_PORT=42420
    - GITLAB_BACKUP_SCHEDULE=weekly
    - GITLAB_BACKUP_EXPIRY=3628800
  volumes:
    - /srv/data/docker/gitlab/data:/home/git/data
  restart: always
redisgitlab:
  image: sameersbn/redis:latest
  restart: always
````

Is this problem on my side (wrong config) or on the image side? :)
