### ISSUE TITLE
docker registry backup

### ISSUE THREAD

**Issue by guybrush** [sameersbn/docker-gitlab#755]
there is a [notice in container_registry.md](https://github.com/sameersbn/docker-gitlab/blame/56ef421b6eb/docs/container_registry.md#L195-L198) that the registry-storage must be mounted in gitlab so it gets backed up. though the volume (`/srv/gitlab/shared/registry`) is [not mounted](https://github.com/sameersbn/docker-gitlab/blame/56ef421b6eb/docs/container_registry.md#L72-L75)? *where* must *what* be mounted? i guess it should be something like that (?):

```
services:
  gitlab:
    volumes:
      - /srv/gitlab/shared/registry:<where should this be mounted?>:Z
      - /srv/gitlab/gitlab:/home/git/data:Z
      - /srv/gitlab/logs:/var/log/gitlab
      - ./certs:/certs
    ...
```
