### ISSUE TITLE
HTTP 500 errors when using CA Trusted Certificate

### ISSUE THREAD

**Issue by patrickc91** [sameersbn/docker-gitlab#775]
I've been working on getting the registry working with my GitLab set up for days now and have had 0 luck whatsoever. I have had success with using self-signed certificates as described in the reference sheet, but I've got a wildcard CA certificate for *.mydomain.com that I would prefer to use.

Here's what I've got:

GitLab Version: 8.8.5
Registry Version: 2.4.1

All running behind an Nginx Reverse Proxy provided by [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy).

Here is my docker-compose.yml:
```
gitlab:
 build: ./gitlab
 container_name: gitlab
 links:
  - redis:redisio
  - postgresql:postgresql
  - registry:registry.mydomain.com

 ports:
  - "10022:22"

 environment:
  - VIRTUAL_HOST=gitdev.mydomain.com

  - GITLAB_HTTPS=true
  - NGINX_X_FORWARDED_PROTO=https
  - GITLAB_GRAVATAR_HTTP_URL=https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon

  - TZ=America/Los_Angeles
  - GITLAB_TIMEZONE=America/Los_Angeles

  - GITLAB_SECRETS_DB_KEY_BASE=<super secret key!>

  - GITLAB_HOST=gitdev.mydomain.com
  - GITLAB_PORT=443
  - GITLAB_SSH_PORT=10022

  - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
  - GITLAB_NOTIFY_PUSHER=false

  - GITLAB_EMAIL=gitlab@mydomain.com
  - GITLAB_EMAIL_REPLY_TO=noreply@mydomain.com
  - GITLAB_INCOMING_EMAIL_ADDRESS=reply@mydomain.com

  - GITLAB_BACKUPS=daily
  - GITLAB_BACKUP_TIME=01:00

  - SMTP_ENABLED=true
  - SMTP_DOMAIN=myinternaldomain
  - SMTP_HOST=<ip address>
  - SMTP_PORT=25

  - IMAP_ENABLED=false

  - GITLAB_PROJECTS_ISSUES=false
  - GITLAB_PROJECTS_WIKI=false
  - GITLAB_PROJECTS_MERGE_REQUESTS=false
  - GITLAB_PROJECTS_CONTAINER_REGISTRY=true

  - GITLAB_REGISTRY_ENABLED=true
  - GITLAB_REGISTRY_HOST=registry.mydomain.com
  - GITLAB_REGISTRY_ISSUER=gitlab-issuer
#  - GITLAB_REGISTRY_API_URL=https://registry.mydomain.com
  - GITLAB_REGISTRY_API_URL=http://registry.mydomain.com
  - GITLAB_REGISTRY_KEY_PATH=/certs/registry.key
  - SSL_REGISTRY_KEY_PATH=/certs/registry.key
  - SSL_REGISTRY_CERT_PATH=/certs/registry.crt

  - LDAP_ENABLED=true
  - LDAP_LABEL=<redacted>
  - LDAP_HOST=<redacted>
  - LDAP_PORT=<redacted>
  - LDAP_UID=<redacted>
  - LDAP_BIND_DN=<redacted>
  - LDAP_PASS=<redacted>
  - LDAP_METHOD=plain
  - LDAP_BASE=<redacted>
  - LDAP_ACTIVE_DIRECTORY=true
  - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=true

 volumes:
  - gitlab_data:/home/git/data:Z
  - gl_registry:/home/git/data/shared/registry:z
#  - ./certs-old:/certs
  - ./certs:/certs

 expose:
  - "22"
  - "80"
  - "443"
  - "10022"
  - "5000"

registry:
 build: ./registry
 container_name: gl_registry
 volumes:
  - gl_registry:/registry:z
#  - ./certs-old:/certs
  - ./certs:/certs
 environment:
  - VIRTUAL_HOST=registry.mydomain.com
  - REGISTRY_LOG_LEVEL=debug
  - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
  - REGISTRY_AUTH_TOKEN_REALM=https://gitdev.mydomain.com/jwt/auth
  - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
  - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
  - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.crt
  - REGISTRY_STORAGE_DELETE_ENABLED=true
  - REGISTRY_HTTP_ADDR=:80
  - REGISTRY_HTTP_HOST=https://registry.mydomain.com
 expose:
  - "80"
  - "443"

redis:
 image: sameersbn/redis:latest
 container_name: gl_redis
 volumes:
  - gitlab_redis_data:/var/lib/redis:Z

postgresql:
 image: sameersbn/postgresql:latest
 container_name: gl_postgresql
 environment:
  - DB_USER=<redacted>
  - DB_PASS=<redacted>
  - DB_NAME=<redacted>
  - DB_EXTENSION=pg_trgm
 volumes:
  - gitlab_db:/var/lib/postgresql:Z
```

I've placed my wildcard certificate into `./certs` while `./certs-old` has my self-signed certificate. All of this is running on HTTPS utilizing the reverse proxy linked above and the very same wildcard certificate I provide to GitLab and the registry.

I'm VERY new when it comes to using SSL/TLS and HTTPS, so I assume I've just configured something very poorly. As it is, when I use the self-signed certificate and set my Docker Daemon to use `--insecure-registry` everything works fine. If I use the wildcard, I get
`Error response from daemon: Get https://registry.mydomain.com/v2/: received unexpected HTTP status: 500 Internal Server Error` from my PC configured with `--insecure-registry` and GitLab gives a 500 error page when I navigate to a repository's container_registry page.

I get `Error response from daemon: Get https://registry.precoa.com/v1/users/: x509: certificate signed by unknown authority` from my Ubuntu box that doesn't have `--insecure-registry` configured.

I also get `404 page not found` when I try `curl --cacert /etc/docker/certs.d/registry.mydomain.com/ca.crt https://registry.mydomain.com/v1/_ping`

If this is a bad place to be requesting aid like this, please direct to me somewhere that people may be able to help. I haven't found anything truly useful online myself yet =/

**Comment by SolidNerd** [comment]
Hey,

first of all what I see is that you using only `8.8.5` but `8.8.5-1` is required to run gitlab registry. Do you run your setup on different Hosts ? So If not I would recommend to proxy without https. It makes a lot of easier to setup.

**Comment by patrickc91** [comment]
Whoops, I only provided the actual version of GitLab I'm running, not the tag I'm using. I am using the `8.8.5-1` image.

Currently have all 4 images that make up my functioning GitLab setup running alongside my reverse proxy image, all on the same host. It took me a little while to get it all working through HTTPS with the self signed certificate, but I finally did. I just really can't seem to get it working with a CA trusted certificate.

Maybe I should try setting this all up without the reverse proxy first? Then try to add the proxy later.

**Comment by SolidNerd** [comment]
Yes. I would try to without a reverse proxy. I use this setup with a let's encrypt certificate and it works like charm.

**Comment by patrickc91** [comment]
Alright. I'll give it a go today without a reverse proxy and utilizing a Let's Encrypt certificate. I've been wanting to try out using a Let's Encrypt certificate for something anyway!

**Comment by patrickc91** [comment]
@SolidNerd Hey, would you mind explaining more about the Certificate needed for `REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE`? I believe this is where my problem lies. My registry only seems to work when I have a self-signed certificate provided for this variable and the `GITLAB_REGISTRY_KEY_PATH` variable.

If I request a new Trusted Certificate, I'm not positive what FQDN to provide or anything like that. It doesn't seem to work with my wildcard certificate as explained previously `*.mydomain.com`, so I'm assuming I need a different certificate.

Gitlab - `https://gitdev.mydomain.com`
Registry - `https://registry.mydomain.com`

Self-signed Certificate - Works
Wild-card Certificate - Fails

**Comment by SolidNerd** [comment]
It could be a self signed certificate or a signed certificate. I don't have any experience with wildcard certificates. But I assume that you need every domain a priv key from the wildcard certificate. Have a look at https://docs.docker.com/registry/configuration/#/token  for the spec and more information.

**Comment by patrickc91** [comment]
After a lot of messing around with various configurations and different certificates, I've resolved the issue. Sadly...I don't know exactly what I did that fixed the problem.

I believe the issues were with my SSL Certificate though. I didn't have the intermediate/root `.crt` combined with my actual wildcard `.crt`, so the SSL chain wasn't complete and failed to verify. Once I combined the two `.crt`'s into a single file and attached it to my Nginx Reverse Proxy and the Gitlab image itself, I stopped getting:
 `Error response from daemon: Get https://registry.precoa.com/v1/users/: x509: certificate signed by unknown authority` when using a docker daemon without the `--insecure-registry` flag set.

As for the 500 error...I assume it was related to my certificate error. It just sort of resolved itself once I figured out the SSL certificate. Here is my final, working `.yml` file if anyone is interested. This is all running behind [jwilder's Nginx proxy](https://github.com/jwilder/nginx-proxy) with a wildcard SSL certificate in place for TLS support. 

The certificate used for authorization between GitLab and the registry is a self signed certificate I made following the instructions in the documentation and is stored in `/auth-certs`. The wildcard SSL certificate is found in `/certs`.

```
gitlab:
 build: ./gitlab
 container_name: gitlab
 restart: always
 links:
  - redis:redisio
  - postgresql:postgresql

 ports:
  - "10022:22"

 environment:
  - VIRTUAL_HOST=git.mydomain.com

  - GITLAB_HTTPS=true
  - NGINX_X_FORWARDED_PROTO=https
  - GITLAB_GRAVATAR_HTTP_URL=https://secure.gravatar.com/avatar/%{hash}?s=%{size}&d=identicon

  - TZ=America/Los_Angeles
  - GITLAB_TIMEZONE=America/Los_Angeles

  - GITLAB_SECRETS_DB_KEY_BASE=<redacted>

  - GITLAB_HOST=git.mydomain.com
  - GITLAB_PORT=443
  - GITLAB_SSH_PORT=10022

  - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
  - GITLAB_NOTIFY_PUSHER=false

  - GITLAB_EMAIL=gitlab@mydomain.com
  - GITLAB_EMAIL_REPLY_TO=noreply@mydomain.com
  - GITLAB_INCOMING_EMAIL_ADDRESS=reply@mydomain.com

  - GITLAB_BACKUPS=daily
  - GITLAB_BACKUP_TIME=01:00

  - SMTP_ENABLED=true
  - SMTP_DOMAIN=<redacted>
  - SMTP_HOST=<redacted>
  - SMTP_PORT=25

  - IMAP_ENABLED=false

  - GITLAB_PROJECTS_ISSUES=false
  - GITLAB_PROJECTS_WIKI=false
  - GITLAB_PROJECTS_MERGE_REQUESTS=false
  - GITLAB_PROJECTS_CONTAINER_REGISTRY=true

  - GITLAB_REGISTRY_ENABLED=true
  - GITLAB_REGISTRY_HOST=registry.mydomain.com
  - GITLAB_REGISTRY_ISSUER=gitlab-issuer
  - GITLAB_REGISTRY_API_URL=http://registry.mydomain.com
  - GITLAB_REGISTRY_KEY_PATH=/auth-certs/registry-auth.key
  - SSL_REGISTRY_KEY_PATH=/certs/mydomain.com.key
  - SSL_REGISTRY_CERT_PATH=/certs/mydomain.com.crt

  - LDAP_ENABLED=true
  - LDAP_LABEL==<redacted>
  - LDAP_HOST=<redacted>
  - LDAP_PORT=<redacted>
  - LDAP_UID=<redacted>
  - LDAP_BIND_DN=<redacted>
  - LDAP_PASS=<redacted>
  - LDAP_METHOD=plain
  - LDAP_BASE=<redacted>
  - LDAP_ACTIVE_DIRECTORY=true
  - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=true

 volumes:
  - gitlab_data:/home/git/data:Z
  - gl_registry:/home/git/data/shared/registry:z
  - ./certs:/certs
  - ./auth-certs:/auth-certs

 expose:
  - "80"
  - "22"
  - "443"
  - "10022"


registry:
 build: ./registry
 container_name: gl_registry
# restart: always
 volumes:
  - gl_registry:/registry:z
  - ./certs:/certs
  - ./auth-certs:/auth-certs

 environment:
  - VIRTUAL_HOST=registry.mydomain.com
  - REGISTRY_LOG_LEVEL=info
  - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
  - REGISTRY_AUTH_TOKEN_REALM=https://git.mydomain.com/jwt/auth
  - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
  - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
  - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/auth-certs/registry-auth.crt
  - REGISTRY_STORAGE_DELETE_ENABLED=true
  - REGISTRY_HTTP_ADDR=:80
  - REGISTRY_HTTP_HOST=https://registry.mydomain.com
  - REGISTRY_HTTP_TLS_CERTFICATE=/certs/mydomain.com.crt
  - REGISTRY_HTTP_TLS_KEY=/certs/mydomain.com.key

 expose:
  - "80"
  - "443"


redis:
 image: sameersbn/redis:latest
 container_name: gl_redis
 restart: always
 volumes:
  - gitlab_redis_data:/var/lib/redis


postgresql:
 image: sameersbn/postgresql:latest
 container_name: gl_postgresql
 restart: always
 environment:
  - DB_USER=<redacted>
  - DB_PASS=<redacted>
  - DB_NAME=<redacted>
  - DB_EXTENSION=pg_trgm
 volumes:
  - gitlab_db:/var/lib/postgresql
```
