### ISSUE TITLE
HTTPS issue after upgrading to 8.10.0

### ISSUE THREAD

**Issue by e11it** [sameersbn/docker-gitlab#800]
HI!

I have configuration:
`docker: nginx-proxy <---> gitlab (vhost)`

My docker-compose (8.9.6-1):
```
gitlab:
  container_name: gitlab
  image: sameersbn/gitlab:8.9.6-1
  links:
    - redis:redis
  external_links:
    - postgres:postgresql
  ports:
    - "22:22"
  environment:
    - VIRTUAL_HOST=
    - LETSENCRYPT_EMAIL=
    - LETSENCRYPT_HOST=
    - DB_HOST=postgresql
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - GITLAB_HOST=
    - GITLAB_SSH_PORT=22
    - GITLAB_HTTPS=true
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - gitlab_data:/home/git/data
```

After upgrade gitlab to 8.10.0 it's become unable to logon: error 422.
The problem was in option: `GITLAB_HTTPS=true`.
So if you have nginx container in front of gitlab  you have to disable option `GITLAB_HTTPS`.

**Issue:** some URL in UI become with http scheme(for example project url now ssl and http).
