### ISSUE TITLE
Upgrading to 8.10.6 fails

### ISSUE THREAD

**Issue by QuickJack** [sameersbn/docker-gitlab#843]
I am currently using GitLab 8.9.6-1 with docker-compose and I am sitting behind a corporate proxy. The update procedure for the postgresql container fails. I am using 9.4-23 and the version recommended for GitLab 8.10.6 is 9.5. I am using GitLab for several month and never had an upgrade problem.

This is part of the output after a docker-compose up:
[33mpostgresql2_1  |[0m Initializing certdir...
[33mpostgresql2_1  |[0m Initializing logdir...
[33mpostgresql2_1  |[0m Initializing rundir...
[33mpostgresql2_1  |[0m Setting resolv.conf ACLs...
[33mpostgresql2_1  |[0m Initializing database...
[33mpostgresql2_1  |[0m ‣ Migrating PostgreSQL 9.4 data to 9.5...
[33mpostgresql2_1  |[0m ‣ Installing PostgreSQL 9.4...
[32mgitlab2_1      |[0m Initializing logdir...
[32mgitlab2_1      |[0m Initializing datadir...
[32mgitlab2_1      |[0m Updating CA certificates...
[33mpostgresql2_1  |[0m W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/trusty-pgdg/InRelease  
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/trusty-pgdg/Release.gpg  Cannot initiate the connection to apt.postgresql.org:80 (2001:4800:1501:1::246). - connect (101: Network is unreachable) [IP: 2001:4800:1501:1::246 80]
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) [IP: 2001:67c:1560:8001::14 80]
[33mpostgresql2_1  |[0m 
[33mpostgresql2_1  |[0m W: Some index files failed to download. They have been ignored, or old ones used instead.
[33mpostgresql2_1  |[0m E: Unable to locate package postgresql-9.4
[33mpostgresql2_1  |[0m E: Couldn't find any package by regex 'postgresql-9.4'
[33mpostgresql2_1  |[0m E: Unable to locate package postgresql-client-9.4
[33mpostgresql2_1  |[0m E: Couldn't find any package by regex 'postgresql-client-9.4'
[33mpostgresql2_1  |[0m ERROR! Failed to install PostgreSQL 9.4. Exiting...
[33m2_postgresql2_1 exited with code 1

**Comment by SolidNerd** [comment]
The problem seems to be with your connection. You currently have no connection and so the package can't be fetched and installed. It starts here:

```
 Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease
```

**Comment by QuickJack** [comment]
My network is reachable but only through a proxy. That's the way how it works in almost all corporate environments. I bet that a lot of people will run into the exact same problem sooner or later.

The env varibale http_proxy must be set. However this not done because GitLab never required this until now. Why does it need postgresql 9.4 to upgrade to 9.5? Why isn't something like that required when updating the gitlab container?

Do you think it's enough to specify http_proxy within docker-compose?

**Comment by QuickJack** [comment]
I upgraded my gitlab instance using postgresql 9.4-24. This worked perfectly. After that I tried to upgrade postgresql to 9.5 which failed like described above. I then added - http_proxy=<ip:port of proxy> to the environment section of the postgresql section. That resolved the upgrade problem. But unfortunately, I cannot login to this server anymore.

**Comment by SolidNerd** [comment]
So to clarify that. You added `http_proxy` to the postgresql container. That is the normal behaviour because Linux uses `http_proxy` as default for enable proxying in applications applications. I don't see why this should be an issue than of our container behaviour, because you can configure your proxy with `http_proxy`. What we can do is to describe this in a separate section / document and show the people how to solve it.

**Comment by QuickJack** [comment]
You are right and I do know how http_proxy works. But something like that was never required in the past.

I think it's a good idea to add some notes on this special upgrade procedure in order to prevent people to hit this problem.

**Comment by kujiy** [comment]
Thank you folks! We got the same error and you saved my life.


#### Only postgresql container test (with the original `docker-compose.yml`)
```yml
version: '2' 

services:
  postgresql:
    image: sameersbn/postgresql:9.5-1
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    env_file:
    - /kc/docker/common/docker-compose-common.env
```

Network didn't work because of proxy.
```
postgresql_1  | W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/binary-amd64/Packages  Something wicked happened resolving 'archive.ubuntu.com:http' (-5 - No address associated with hostname)
```

#### Added `http_proxy` to yml
```yml
version: '2' 

services:
  postgresql:
    image: sameersbn/postgresql:9.5-1
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    environment:
    - http_proxy=http://id:password@my-proxy.example.com:3128
```

Worked well.
```
postgresql_1  | Initializing datadir...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | Starting PostgreSQL 9.5...
postgresql_1  | LOG:  database system was shut down at 2016-08-23 14:44:43 JST
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  autovacuum launcher started
postgresql_1  | LOG:  database system is ready to accept connections
```


#### Alternative; Using `env_file` instead of `environment`
```yml
version: '2' 

services:
  postgresql:
    image: sameersbn/postgresql:9.5-1
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    env_file:
    - /common/docker-compose.env
```

Also worked well!
```
postgresql_1  | Initializing datadir...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | Creating database user: gitlab
postgresql_1  | Creating database: gitlabhq_production...
postgresql_1  | ‣ Loading pg_trgm extension...
postgresql_1  | ‣ Granting access to gitlab user...
postgresql_1  | Starting PostgreSQL 9.5...
postgresql_1  | LOG:  database system was shut down at 2016-08-23 14:45:27 JST
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  autovacuum launcher started
postgresql_1  | LOG:  database system is ready to accept connections
```




Thank you so much!!!
