### ISSUE TITLE
Not being able to log onto the docker registry

### ISSUE THREAD

**Issue by lenovouser** [sameersbn/docker-gitlab#869]
Followed your documentation, tried self-signed and certificates signed by a authority.

I am getting this error every time I try to log in:

```
Error response from daemon: login attempt to https://registry.domain.tld/v2/ failed with status: 401 Unauthorized
```

**The Docker Compose Files:**
<details>
<summary>**registry/docker-compose.yml**</summary>
```yml
version: '2'

services:

  cache-registry:
    restart: always
    container_name: cache-registry
    image: redis:3.2-alpine
    networks:
     - cache

  registry:
    restart: always
    container_name: registry
    image: registry:2.5
    domainname: domain.tld
    hostname: registry
    dns:
     - 8.8.8.8
     - 8.8.4.4
    networks:
     - registry
    depends_on:
     - cache-registry
    links:
     - cache-registry:redis
    volumes:
    - /domain/data/registry:/registry:Z
    - /domain/ssl:/ssl:ro
    environment:
    - REGISTRY_LOG_LEVEL=debug

    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry

    #- REGISTRY_STORAGE=s3
    #- REGISTRY_STORAGE_S3_ACCESSKEY=secret
    #- REGISTRY_STORAGE_S3_SECRETKEY=secret
    #- REGISTRY_STORAGE_S3_REGION=global
    #- REGISTRY_STORAGE_S3_REGIONENDPOINT=https://storage.domain.tld
    #- REGISTRY_STORAGE_S3_BUCKET=registry-docker

    - REGISTRY_AUTH_TOKEN_REALM=https://code.domain.tld/jwt/auth
    - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
    - REGISTRY_AUTH_TOKEN_ISSUER=COMPANY LLC.
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/registry.domain.tld.rsa.crt

    - REGISTRY_REDIS_ADDR=redis:6379
    - REGISTRY_REDIS_DB=0

    - REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis

    - REGISTRY_STORAGE_DELETE_ENABLED=true

networks:
  registry:
    external: true
  cache:
    external: true
```
</details>

<details>
<summary>**code/docker-compose.yml**</summary>
```yml
version: '2'

services:
  cache-code:
    restart: always
    container_name: cache-code
    image: sameersbn/redis:latest
    networks:
     - cache
    command:
    - --loglevel warning
    volumes:
      - /domain/data/code/cache:/var/lib/redis:Z

  code:
    restart: always
    container_name: code
    image: sameersbn/gitlab:8.11.0
    domainname: domain.tld
    hostname: code
    dns:
     - 8.8.8.8
     - 8.8.4.4
    networks:
     - nginx
     - cache
     - postgresql
     - storage
     - code
     - registry
    depends_on:
      - cache-code
    ports:
    - "<ip>:22:22"
    external_links:
    - postgresql:postgresql
    - registry:registry
    links:
    - cache-code:redis
    volumes:
    - /domain/data/code:/home/git/data:Z
    - /domain/data/registry:/home/git/data/shared/registry:Z
    - /domain/ssl:/home/git/ssl:ro
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=code
    - DB_PASS=<pass>
    - DB_NAME=code

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Berlin
    - GITLAB_TIMEZONE=Berlin

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=code.domain.tld
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=22

    - GITLAB_SECRETS_SECRET_KEY_BASE=<secret>
    - GITLAB_SECRETS_DB_KEY_BASE=<secret>
    - GITLAB_SECRETS_OTP_KEY_BASE=<secret>

    - GITLAB_ROOT_EMAIL=administrator@domain.tld
    - GITLAB_ROOT_PASSWORD=<pass>

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=code@domain.tld

    - GITLAB_REGISTRY_ENABLED=true
    - GITLAB_REGISTRY_HOST=registry.domain.tld
    - GITLAB_REGISTRY_PORT=5005
    - GITLAB_REGISTRY_API_URL=https://registry.domain.tld
    - GITLAB_REGISTRY_KEY_PATH=/home/git/ssl/registry.domain.tld.rsa.key

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=domain.tld
    - SMTP_HOST=smtp.sendgrid.net
    - SMTP_PORT=587
    - SMTP_USER=code@domain.tld
    - SMTP_PASS=<pass>
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false

networks:
  nginx:
    external: true
  cache:
    external: true
  postgresql:
    external: true
  storage:
    external: true
  code:
    external: true
  registry:
    external: true
```
</details>

I am proxying **both** GitLab and the Registry through another Load Balancer Container for adding e.g. valid SSL certificates:

```
                                                                 +---------------+
                                 +-------+ +-------------------> | registry:5000 |
                                 |       |                       +---------------+
https://registry.domain.tld ---> |       |
                                 |       |
                                 | NGINX |
                                 |       |
    https://code.domain.tld ---> |       |
                                 |       |                       +---------------+
                                 +-------+ +-------------------> | code:80       |
                                                                 +---------------+
```

**NGINX configuration:**

<details>
<summary>**registry.domain.tld**</summary>
```
upstream registry {
    ip_hash;
    server registry:5000;
}

server {
    listen      443 ssl http2;
    listen [::]:443 ssl http2;

    ssl on;

    ssl_certificate     /etc/ssl/domain.tld.rsa.bundle.crt;
    ssl_certificate_key /etc/ssl/domain.tld.rsa.key;

    ssl_certificate     /etc/ssl/domain.tld.ecc.bundle.crt;
    ssl_certificate_key /etc/ssl/domain.tld.ecc.key;

    ssl_stapling               on;
    ssl_stapling_verify        on;
    resolver                   8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout           5s;

    server_name registry.domain.tld;

    location / {

        proxy_set_header Host              $http_host;
        proxy_set_header Referer           $http_referer;
        proxy_set_header Referrer          $http_referer;
        proxy_set_header Cookie            $http_cookie;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-NGINX-Proxy     true;
        proxy_set_header X-Forwarded-SSL   on;

        proxy_redirect                     off;
        proxy_http_version                 1.1;

        proxy_pass                         http://registry;
    }
}
```
</details>

<details>
<summary>**code.domain.tld**</summary>
```
upstream code {
    ip_hash;
    server code:80;
}

server {
    listen      443 ssl http2;
    listen [::]:443 ssl http2;

    ssl on;

    ssl_certificate     /etc/ssl/domain.tld.rsa.bundle.crt;
    ssl_certificate_key /etc/ssl/domain.tld.rsa.key;

    ssl_certificate     /etc/ssl/domain.tld.ecc.bundle.crt;
    ssl_certificate_key /etc/ssl/domain.tld.ecc.key;

    ssl_stapling               on;
    ssl_stapling_verify        on;
    resolver                   8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout           5s;

    server_name code.domain.tld;

    location / {

        proxy_set_header Host              $http_host;
        proxy_set_header Referer           $http_referer;
        proxy_set_header Referrer          $http_referer;
        proxy_set_header Cookie            $http_cookie;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_set_header X-NGINX-Proxy     true;
        proxy_set_header X-Forwarded-SSL   on;

        proxy_redirect                     off;
        proxy_http_version                 1.1;

        proxy_pass                         http://code;
    }
}
```
</details>

Any ideas? I have also tried different things like proxying into the `code` container with port `5005` instead of proxying directly into the registry container. Or e.g. using `http://registry:5000` for `GITLAB_REGISTRY_API_URL` instead of `https://registry.domain.tld`. 😢
