### ISSUE TITLE
Docker Registry page error 500 ( ErrorPage: serving predefined error page: 500)

### ISSUE THREAD

**Issue by alogoc** [sameersbn/docker-gitlab#892]
Issue:

This seems like  a long term issue similar to #18825  #18736 #21445  which hasn't been permanently solved yet.

How to reproduce: 

1.     Create repo;
2.     Allow Container Registry ;
3.     From my machine login and push image (used alpine for testing because it is small, but seems to happen with any image);
4.     In the repo page, click the Container Registry menu.

Here is the production log:

```
==> /home/git/gitlab/log/production.log <==
Started GET "/Taranis/taranis/container_registry" for 10.2.13.3 at 2016-09-19 12:17:03 +0200
Processing by Projects::ContainerRegistryController#index as HTML
  Parameters: {"namespace_id"=>"Taranis", "project_id"=>"taranis"}
Completed 500 Internal Server Error in 83ms (ActiveRecord: 6.9ms)

URI::InvalidURIError (query conflicts with opaque):
  lib/container_registry/client.rb:19:in `repository_tags'
  lib/container_registry/repository.rb:22:in `manifest'
  lib/container_registry/repository.rb:31:in `tags'
  app/controllers/projects/container_registry_controller.rb:8:in `index'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'


Docker version


Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:
 OS/Arch:      linux/amd64```

OS Version:

NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by solidnerd** [comment]
Hey,
which version of docker/distribution do you use ? This seems to be a problem that your registry supports only the manifest v1 spec. I would recommend to upgrade to docker/distribution:2.4.1 or something higher like I said in the documentation. Could you post your `docker-compose.yml`

**Comment by alogoc** [comment]
Hi,

Thanks your reply. 

I am using latest version of the official docker registry (2.5.1). Everything is hosted on CoreOS (as mentioned above) and Kubernetes. 


```
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-registry
  namespace: gitlab
  labels:
    k8s-app: gitlab-registry
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: gitlab-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: gitlab-registry
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2.5.1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 200Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: ":5000"
        - name: REGISTRY_STORAGE
          value: "s3"
        - name: REGISTRY_STORAGE_S3_ACCESSKEY
          value: "xxxxxx"
        - name: REGISTRY_STORAGE_S3_SECRETKEY
          value: "xxxxx"
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: "gitlab-container-registry"
        - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
          value: "xxxxxx"
        - name: REGISTRY_STORAGE_S3_REGION
          value: "eu"
        - name: REGISTRY_STORAGE_S3_ENCRYPT
          value: "true"
        - name: REGISTRY_STORAGE_S3_SECURE
          value: "true"
        - name: REGISTRY_STORAGE_S3_V4AUTH
          value: "true"
        - name: REGISTRY_STORAGE_S3_CHUNKSIZE
          value: "5242880"
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: "redis"
        - name: REGISTRY_REDIS_ADDR
          value: "redis.gitlab.svc.cluster.local"
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: "https://xxxx/jwt/auth"
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "container_registry"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "gitlab-issuer"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: "/certs/registry-auth.crt"
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_HTTP_SECRET
          value: "xxxxx"
        - name: REGISTRY_HTTP_RELATIVEURLS
          value: "true"
        volumeMounts:
        - name: cert-dir
          mountPath: /certs
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      - name: registry-ui
        image: alogoc/docker-registry-frontend
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: "localhost"
        - name: ENV_DOCKER_REGISTRY_PORT
          value: "5000"
        ports:
        - containerPort: 80
          name: registry
          protocol: TCP
      volumes:
      - name: cert-dir
        secret:
          secretName: gitlab-container-registry-secret
      nodeSelector:
        label: worker
```

**Comment by solidnerd** [comment]
Could you post your gitlab configuration aswell ? I find currently no error.

**Comment by alogoc** [comment]
Here is my gitlab-rc.yaml : 

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    name: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:8.11.5
        env:
        - name: TZ
          value: Europe/Berlin
        - name: GITLAB_TIMEZONE
          value: Berlin

        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: "xxxxxxxxx"
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: "xxxxxxxxxxxx"
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: "xxxxxxxxxxxxx"
        - name: GITLAB_REGISTRY_ENABLED
          value: "true"
        - name: GITLAB_REGISTRY_HOST
          value: "xxxxxxxxx"
        - name: GITLAB_REGISTRY_PORT
          value: "5000"
        - name: GITLAB_REGISTRY_API_URL
          value: "gitlab-registry.gitlab.svc.cluster.local:5000"
        - name: GITLAB_REGISTRY_KEY_PATH
          value: "/certs/registry-auth.key"
        - name: SSL_REGISTRY_KEY_PATH
          value: "/certs/registry.key"
        - name: SSL_REGISTRY_CERT_PATH
          value: "/certs/registry.crt"
        - name: NGINX_ENABLED
          value: "false"
        - name: NGINX_HSTS_ENABLED
          value: "false"
        - name: GITLAB_HTTPS
          value: "false"
        - name: SSL_SELF_SIGNED
          value: "true"
        - name: SSL_VERIFY_CLIENT
          value: "false"



        - name: GITLAB_ROOT_PASSWORD
          value: xxxx
        - name: GITLAB_ROOT_EMAIL
          value: xxxxxxxx

        - name: GITLAB_HOST
          value: xxxxxxx
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00


        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: xxxxx
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"

        - name: SMTP_ENABLED
          value: "enabled"
        - name: SMTP_DOMAIN
          value: gmail.com
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: xxxxxxx
        - name: SMTP_PASS
          value: xxxxxxx
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        - name: registry
          containerPort: 5000
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        - name: cert-dir
          mountPath: /certs
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-git-pvc
      - name: cert-dir
        secret:
          secretName: gitlab-container-registry-secret
      nodeSelector:
        label: worker
```
