### ISSUE TITLE
Access denied, Timeout and config file problems

### ISSUE THREAD

**Issue by Alas89** [sameersbn/docker-gitlab#96]
Hello Guys,

I`m relatively new in the howl docker world. So I run into some problems with your gitlab docker container.

The first one is: I pulled and run the container. The webfrontend is running fine. I added useres, created a group and project and uploaded my rsa key. But now when I want to pull the project I recive a access denied message.

Second: To fix this I changed the config files from default to:
              gitlab-shell/config.yml
                           # Url to gitlab instance. Used for api calls. Should end with a slash.
                           gitlab_url: "http://mydomain:80/"

```
          gitlab/config/gitlab.yml
                       ## Web server settings
                       host: mydomain
                       port: 80

                       # If you use non-standard ssh port you need to specify it
                       ssh_port: 2222

                       test:
                              <<: *base
                           gravatar:
                                 enabled: true
                            gitlab:
                            host: mydomain
                            port: 80
```

After this I run into a timeout 

The third and last problem is when I restart the docker container with docker restart <container id> all the changes are restored to the default vallue.

The containers port forwarding is 2222:22 and 80:80.

I used three different RSA-keys all get the access denied.

Thanks ahead for your response. I hope you can help me . I am pretty frustrated now :(
