### ISSUE TITLE
Upgrading from legacy installation

### ISSUE THREAD

**Issue by mindriven** [sameersbn/docker-gitlab#973]
Hi @sameersbn,
Long time ago I've installed gitlab from sources. Today I've updated this old installation to version 7.9.1, which is also old, but something that seems to be supported by your project (judging from tag). I believed that after I'll do so I can install dockerized version of gitlab and restore previously made backup on it, and then updating it to current version should be somehow easier/automatic.

I took the current version of docker-compose.yml and naively updated version of gitlab image. This however didn't work, console output is presented below. After taking a short look at commit tagged 7.9.1 I assume that this old gitlab image does ignore database settings from docker-compose.yml.

Now I'm asking myself if this will be possible to do what I wanted to do. Is this scenario (migrate to older version+upgrade) supported? I've googled and didn't find anything useful.

I also believe there are more people in the situation similar to main. Some guidance on how to progress would greatly appreciated.

``` bash
Starting dockerongitlab_redis_1
Starting dockerongitlab_postgresql_1
Recreating dockerongitlab_gitlab_1
Attaching to dockerongitlab_redis_1, dockerongitlab_postgresql_1, dockerongitlab_gitlab_1
redis_1       | Starting redis-server...
postgresql_1  | Initializing datadir...
postgresql_1  | Initializing certdir...
postgresql_1  | Initializing logdir...
postgresql_1  | Initializing rundir...
postgresql_1  | Setting resolv.conf ACLs...
postgresql_1  | Creating database user: gitlab
postgresql_1  | Creating database: gitlabhq_production...
postgresql_1  | ÔÇú Loading pg_trgm extension...
postgresql_1  | ÔÇú Granting access to gitlab user...
postgresql_1  | Starting PostgreSQL 9.5...
postgresql_1  | LOG:  database system was shut down at 2016-11-17 13:52:34 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  | LOG:  autovacuum launcher started
gitlab_1      | Waiting for database server to accept connections...........................................................dockerongitlab_gitlab_1 exited with code 1
gitlab_1      | Waiting for database server to accept connections...........................................................
gitlab_1      | Waiting for database server to accept connections...........................................................
gitlab_1      | Waiting for database server to accept connections...........................................................
dockerongitlab_gitlab_1 exited with code 1
gitlab_1      | Waiting for database server to accept connections...........................................................
gitlab_1      | Waiting for database server to accept connections...........................................................
<<<<last line is repeated more times>>>>
```

**Comment by GJRTimmer** [comment]
Can you post the docker-compose.yml, and remove any passwords / sensitive values from it.
You might need a more basic variant of a docker-compose.

**Comment by mindriven** [comment]
Sure, with pleasure. The file that I've used is presented below.
BTW I got gitlab 7.9.1 spinning on my docker-machine but without using docker-compose. I've talked with docker directly. Command that got me going is:

```bash
docker run --name=gitlab  -e 'DB_TYPE=postgres' -e 'DB_HOST=postgresql' -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=gitlab' -e 'DB_PASS=password' -e 'GITLAB_PORT=10080' -e 'GITLAB_SSH_PORT=10022' -p 10022:22 -p 10080:80 -v /opt/gitlab/data:/home/git/data  --link postgresql:postgresql --link redis:redisio sameersbn/gitlab:7.9.1
```

And now docker-compose that failed for me:

```yml
version: '2'

services:
   redis:
     image: sameersbn/redis:latest
     volumes:
     - /srv/docker/gitlab/redis:/var/lib/redis:Z

   postgresql:
     image: sameersbn/postgresql:9.4
     volumes:
     - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
     environment:
     - DB_USER=gitlab
     - DB_PASS=secretpassword
     - DB_NAME=gitlabhq_production

   gitlab:
     image: sameersbn/gitlab:7.9.1
     volumes:
     - /srv/docker/gitlab/gitlab:/home/git/data:Z
     depends_on:
     - redis
     - postgresql
     ports:
     - "10080:80"
     - "10022:22"
     environment:
     - DEBUG=false
     - DB_TYPE=postgres #added because gitlab explicitly asked for it during the startup
     - DB_ADAPTER=postgresql
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_USER=gitlab
     - DB_PASS=password
     - DB_NAME=gitlabhq_production
     
     - REDIS_HOST=redis
     - REDIS_PORT=6379
```

**Comment by solidnerd** [comment]
Hey @mindriven,

at first view I see that your `DB_HOST`  in your docker-compose.yml ist not correct, because you use 2 two different mechanisms. At the docker run command you use links to inter communication between your containers. In your docker-compose.yml you use networks. The problem is here that in a docker network you can you the normal container name. In your case it would postgresql. Try to ping it from the gitlab container. I hope that I could help .

**Comment by GJRTimmer** [comment]
I think you have to add the links section, now your host can be found. I've not included the possible fix from @solidnerd 
```
version: '2'

services:
   redis:
     image: sameersbn/redis:latest
     volumes:
     - /srv/docker/gitlab/redis:/var/lib/redis:Z

   postgresql:
     image: sameersbn/postgresql:9.4
     volumes:
     - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
     environment:
     - DB_USER=gitlab
     - DB_PASS=secretpassword
     - DB_NAME=gitlabhq_production

   gitlab:
     image: sameersbn/gitlab:7.9.1
     volumes:
     - /srv/docker/gitlab/gitlab:/home/git/data:Z
     depends_on:
     - redis
     - postgresql
     links:
       - redis:redis
       - postgresql:postgres
     ports:
     - "10080:80"
     - "10022:22"
     environment:
     - DEBUG=false
     - DB_TYPE=postgres #added because gitlab explicitly asked for it during the startup
     - DB_ADAPTER=postgresql
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_USER=gitlab
     - DB_PASS=password
     - DB_NAME=gitlabhq_production

     - REDIS_HOST=redis
     - REDIS_PORT=6379
```

**Comment by mindriven** [comment]
Thanks for help guys! I got it working using this file attached below.
BTW. can any one please comment if my plan of updating gitlab after dockerizing it is a sane/recommended way? Or can you already predict a showstopper or a better way?

```yml
version: '2'

services:
   redis:
     image: sameersbn/redis:latest
     volumes:
     - /srv/docker/gitlab/redis:/var/lib/redis:Z

   postgresql:
     image: sameersbn/postgresql:9.5-3
     volumes:
     - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
     environment:
     - DB_USER=gitlab
     - DB_PASS=password
     - DB_NAME=gitlabhq_production

   gitlab:
     image: sameersbn/gitlab:7.9.1
     volumes:
     - /srv/docker/gitlab/gitlab:/home/git/data:Z
     depends_on:
     - redis
     - postgresql
     ports:
     - "10080:80"
     - "10022:22"
     environment:
     - DEBUG=false
     - DB_TYPE=postgres #added because gitlab explicitly asked for it during the startup
     - DB_ADAPTER=postgresql
     - DB_HOST=postgresql
     - DB_PORT=5432
     - DB_USER=gitlab
     - DB_PASS=password
     - DB_NAME=gitlabhq_production

     - REDIS_HOST=redis
     - REDIS_PORT=6379
```
